// mewa-code/webui/src/chat/chat-view.tsx
import type { AskUserQuestionResult, PromptHit, QueueLane } from "@mewa-code/contracts";
import { ArrowDown } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Virtuoso, type VirtuosoHandle } from "react-virtuoso";
import { EMPTY_RUNTIME, selectProjectAreaById, toast, useAppStore } from "@/store";
import { errorText, getTransport } from "@/transport";
import { AskStatesContext, deriveAskStates } from "./ask-state";
import { type ChatActions, ChatActionsContext } from "./chat-actions";
import { ChatHeader } from "./chat-header";
import {
	Composer,
	type ComposerHandle,
	type MentionCandidate,
	type SubmitBehavior,
} from "./composer";
import { ExtUiDialog } from "./ext-ui-dialog";
import { HistoryOverlay } from "./history-overlay";
import { QueueStrip } from "./queue-strip";
import { type ChatRow, deriveRows, rowIndexForTurn } from "./rows";
import { SessionGoalControl } from "./session-goal-control";
import { StreamIndicator, type StreamStatus, streamStatus } from "./stream-indicator";
import "./tools/register";
import { ChatTurnView } from "./turns";
import type { ChatAttachment, ChatTurn } from "./types";
import { useChatScroll } from "./use-chat-scroll";
import { useHistorySearch } from "./use-history-search";

function turnAnchorText(turn: ChatTurn): string {
	if (turn.kind === "user") {
		const { content } = turn.message;
		return typeof content === "string"
			? content
			: content
					.filter((b) => b.type === "text")
					.map((b) => b.text)
					.join("\n");
	}
	if (turn.kind === "assistant") {
		return turn.message.content
			.filter((b) => b.type === "text")
			.map((b) => b.text)
			.join("\n");
	}
	return "";
}

type ChatListContext = { status: StreamStatus | null };

function StreamFooter({ context }: { context: ChatListContext }) {
	if (!context.status) return null;
	return (
		<div className="mx-auto max-w-3xl px-md pb-sm">
			<StreamIndicator status={context.status} />
		</div>
	);
}

const CHAT_LIST_COMPONENTS = { Footer: StreamFooter };

export default function ChatView({
	sessionId,
	projectAreaId,
}: {
	sessionId: string;
	projectAreaId: string;
}) {
	const runtime = useAppStore((s) => s.sessions[sessionId]) ?? EMPTY_RUNTIME;
	const projectId = useAppStore(
		(state) =>
			Object.values(state.projectAreas)
				.flat()
				.find((projectArea) => projectArea.id === projectAreaId)?.projectId,
	);
	const projectAreaRoot = useAppStore(
		(s) => selectProjectAreaById(s, projectAreaId)?.root ?? undefined,
	);
	const projectAreas = useAppStore((s) => s.projectAreas);
	const projectAreaNames = useMemo(() => {
		const map: Record<string, string> = {};
		for (const list of Object.values(projectAreas)) {
			for (const w of list) map[w.id] = w.name;
		}
		return map;
	}, [projectAreas]);
	const {
		turns,
		toolResults,
		isStreaming,
		currentAssistantId,
		stats,
		commands,
		draft,
		queue,
		pendingExtUi,
		extUiStatus,
		extUiWidget,
		model: sessionModel,
		thinkingLevel,
	} = runtime;

	const headerStatusEntries = useMemo<[string, string][]>(() => {
		const entries = Object.entries(extUiStatus);
		if (sessionModel) entries.push(["mewa-model", sessionModel.name || sessionModel.id]);
		entries.push(["mewa-reasoning", thinkingLevel]);
		return entries;
	}, [extUiStatus, sessionModel, thinkingLevel]);

	const rows = useMemo(
		() => deriveRows(turns, toolResults, isStreaming),
		[turns, toolResults, isStreaming],
	);

	const listContext = useMemo<ChatListContext>(() => {
		const last = turns[turns.length - 1];
		const status =
			isStreaming && last?.kind !== "retry" ? streamStatus(turns, currentAssistantId) : null;
		return { status };
	}, [turns, isStreaming, currentAssistantId]);

	const recentPrompts = useMemo(() => {
		const texts = turns
			.filter((t) => t.kind === "user")
			.map((t) => turnAnchorText(t))
			.filter(Boolean);
		return [...new Set(texts.reverse())];
	}, [turns]);

	const [mentionQuery, setMentionQuery] = useState<string | null>(null);
	const [mentionCandidates, setMentionCandidates] = useState<MentionCandidate[]>([]);

	const virtuosoRef = useRef<VirtuosoHandle>(null);
	const { followOutput, handleAtBottom, showScrollButton, scrollToBottom, containerProps } =
		useChatScroll(virtuosoRef);
	const composerRef = useRef<ComposerHandle>(null);
	const askFocusScope = useRef<object>({}).current;

	const {
		state: historyState,
		openOverlay,
		close: closeHistory,
		setQuery,
		cycleScope,
		setScope,
		toggleStage,
		moveSelection,
		openMessage,
	} = useHistorySearch(sessionId, projectAreaId, projectId);

	const chatLocationRequest = useAppStore((s) => s.chatLocationRequest);
	const [flashRowId, setFlashRowId] = useState<string | null>(null);

	useEffect(() => {
		getTransport()
			.request("session.getCommands", { sessionId })
			.then((c) => useAppStore.getState().setCommands(sessionId, c))
			.catch(() => {});
	}, [sessionId]);

	const mergedCommands = commands;

	// biome-ignore lint/correctness/useExhaustiveDependencies: `isStreaming` is the refetch trigger, not read
	useEffect(() => {
		getTransport()
			.request("session.getStats", { sessionId })
			.then((st) => useAppStore.getState().setStats(sessionId, st))
			.catch(() => {});
	}, [sessionId, isStreaming]);

	useEffect(() => {
		if (mentionQuery === null) {
			setMentionCandidates([]);
			return;
		}
		const slash = mentionQuery.lastIndexOf("/");
		const dir = slash >= 0 ? mentionQuery.slice(0, slash) : "";
		const prefix = (slash >= 0 ? mentionQuery.slice(slash + 1) : mentionQuery).toLowerCase();
		let cancelled = false;
		const timer = setTimeout(() => {
			getTransport()
				.request("fs.readDir", { projectId: projectAreaId, root: projectAreaRoot ?? "", path: dir })
				.then((nodes) => {
					if (cancelled) return;
					setMentionCandidates(
						nodes
							.filter((n) => n.name.toLowerCase().startsWith(prefix))
							.slice(0, 12)
							.map((n) => ({ path: n.path, name: n.name, kind: n.kind })),
					);
				})
				.catch(() => {
					if (!cancelled) setMentionCandidates([]);
				});
		}, 120);
		return () => {
			cancelled = true;
			clearTimeout(timer);
		};
	}, [mentionQuery, projectAreaId, projectAreaRoot]);

	const onMentionQuery = useCallback((q: string | null) => setMentionQuery(q), []);

	const restoreTextToDraft = (text: string) => {
		if (!text.trim()) return;
		const current = useAppStore.getState().sessions[sessionId]?.draft ?? "";
		const combined = [text, current].filter((t) => t.trim()).join("\n\n");
		useAppStore.getState().setChatDraft(sessionId, combined);
		composerRef.current?.refocus();
	};

	const performSend = (
		text: string,
		attachments: ChatAttachment[],
		behavior: Exclude<SubmitBehavior, "interrupt">,
	) => {
		const queued = behavior !== "send";
		if (!queued && (text || attachments.length > 0))
			useAppStore.getState().appendUserMessage(sessionId, text, attachments);
		const images = attachments.map((a) => a.content);
		const params = { sessionId, text, ...(images.length > 0 ? { images } : {}) };
		const method =
			behavior === "steer"
				? "session.steer"
				: behavior === "followUp"
					? "session.followUp"
					: "session.prompt";
		getTransport()
			.request(method, params)
			.catch((err) => {
				useAppStore.getState().appendErrorTurn(sessionId, errorText(err));
				if (queued) restoreTextToDraft(text);
			});
	};

	const onSubmit = (text: string, attachments: ChatAttachment[], behavior: SubmitBehavior) => {
		if (behavior !== "interrupt") {
			performSend(text, attachments, behavior);
			return;
		}
		getTransport()
			.request("session.abort", { sessionId })
			.then(() => performSend(text, attachments, "send"))
			.catch((err) => {
				useAppStore.getState().appendErrorTurn(sessionId, errorText(err));
				restoreTextToDraft(text);
			});
	};

	const removeQueued = (kind: QueueLane, index: number) =>
		getTransport().request("session.removeQueued", { sessionId, kind, index });

	const onEditQueued = (kind: QueueLane, index: number) =>
		void removeQueued(kind, index)
			.then(({ removed }) => {
				if (removed !== null) restoreTextToDraft(removed);
			})
			.catch(() => {});

	const onRemoveQueued = (kind: QueueLane, index: number) =>
		void removeQueued(kind, index).catch(() => {});

	const restoreQueueToDraft = async (): Promise<void> => {
		const { steering, followUp } = await getTransport().request("session.clearQueue", {
			sessionId,
		});
		restoreTextToDraft([...steering, ...followUp].join("\n\n"));
	};

	const onAbort = () => {
		void restoreQueueToDraft().catch(() => {});
		getTransport()
			.request("session.abort", { sessionId })
			.catch(() => {});
	};

	const onHistoryOpen = () => openOverlay(draft);

	const onDismissHistory = () => {
		closeHistory();
		composerRef.current?.refocus();
	};

	const onInsertHit = (hit: PromptHit) => {
		composerRef.current?.insertText(hit.text);
		closeHistory();
	};

	const onInsertAndSendHit = (hit: PromptHit) => {
		composerRef.current?.insertAndSubmit(hit.text, isStreaming ? "followUp" : "send");
		closeHistory();
	};

	const onDeleteHistoryChat = async (targetProjectAreaId: string, targetSessionId: string) => {
		try {
			await getTransport().request("session.delete", {
				projectId: targetProjectAreaId,
				sessionId: targetSessionId,
			});
			closeHistory();
			useAppStore.getState().deleteChat(targetProjectAreaId, targetSessionId);
		} catch (err) {
			toast.error(errorText(err), "Couldn't delete the chat");
		}
	};

	useEffect(() => {
		if (
			!chatLocationRequest ||
			chatLocationRequest.projectAreaId !== projectAreaId ||
			chatLocationRequest.sessionId !== sessionId ||
			rows.length === 0
		) {
			return;
		}
		if (useAppStore.getState().chatLocationRequest !== chatLocationRequest) return;
		const { messageIndex, anchorText } = chatLocationRequest;
		const prefix = anchorText.slice(0, 40);
		const mappedId = runtime.turnIdByMessageIndex?.[messageIndex];
		const mapped = mappedId ? turns.find((t) => t.id === mappedId) : undefined;
		const target =
			mapped && turnAnchorText(mapped).includes(prefix)
				? mapped
				: turns.findLast((t) => turnAnchorText(t).includes(prefix));
		const index = target ? rowIndexForTurn(rows, target.id) : -1;
		if (index === -1) {
			toast.error("couldn't locate the message — the session may have changed");
			useAppStore.getState().clearChatLocation();
			return;
		}
		virtuosoRef.current?.scrollToIndex({ index, align: "center" });
		setFlashRowId(rows[index]?.id ?? null);
		useAppStore.getState().clearChatLocation();
	}, [chatLocationRequest, sessionId, rows, runtime.turnIdByMessageIndex, turns, projectAreaId]);

	const historyOpenRequest = useAppStore((s) => s.historyOpenRequest);
	const historyOverlayOpen = historyState.open;
	useEffect(() => {
		if (historyOpenRequest?.sessionId !== sessionId) return;
		if (useAppStore.getState().historyOpenRequest !== historyOpenRequest) return;
		useAppStore.getState().clearHistoryOpen();
		if (historyOverlayOpen) cycleScope();
		else composerRef.current?.openHistory();
	}, [historyOpenRequest, sessionId, historyOverlayOpen, cycleScope]);

	useEffect(() => {
		if (flashRowId === null) return;
		const timer = setTimeout(() => setFlashRowId(null), 1600);
		return () => clearTimeout(timer);
	}, [flashRowId]);

	const onOpenChange = useCallback(
		(path: string) => {
			useAppStore.getState().requestChangesView(projectAreaId, path);
		},
		[projectAreaId],
	);

	const askStates = useMemo(
		() => deriveAskStates(runtime.turns, runtime.askAnswers),
		[runtime.turns, runtime.askAnswers],
	);
	const askContext = useMemo(
		() => ({ states: askStates, focusScope: askFocusScope }),
		[askStates, askFocusScope],
	);

	const chatActions = useMemo<ChatActions>(
		() => ({
			answerQuestion: (toolCallId: string, result: AskUserQuestionResult) =>
				getTransport()
					.request("session.answerQuestion", { sessionId, toolCallId, result })
					.then(() => undefined),
			focusComposer: () => composerRef.current?.refocus(),
		}),
		[sessionId],
	);

	const onExtUiReply = (value: string | boolean | null) => {
		if (!pendingExtUi) return;
		const id = pendingExtUi.id;
		useAppStore.getState().clearPendingExtUi(sessionId, id);
		getTransport()
			.request("session.extUiReply", { response: { id, value } })
			.catch(() => {});
	};

	const widgetEntries = Object.entries(extUiWidget);

	return (
		<ChatActionsContext.Provider value={chatActions}>
			<AskStatesContext.Provider value={askContext}>
				<div className="flex h-full min-h-0 flex-col bg-container-projectArea-bg">
					<div className="shrink-0">
						<ChatHeader
							stats={stats}
							statusEntries={headerStatusEntries}
							left={<SessionGoalControl projectAreaId={projectAreaId} sessionId={sessionId} />}
						/>
					</div>
					<div
						data-testid="chat-scroll"
						className="relative flex min-h-0 flex-1 flex-col"
						{...containerProps}
					>
						<Virtuoso<ChatRow, ChatListContext>
							ref={virtuosoRef}
							data={rows}
							context={listContext}
							components={CHAT_LIST_COMPONENTS}
							className="min-h-0 flex-1 overflow-x-hidden"
							initialTopMostItemIndex={{ index: Math.max(rows.length - 1, 0), align: "end" }}
							followOutput={followOutput}
							atBottomStateChange={handleAtBottom}
							atBottomThreshold={50}
							computeItemKey={(_, row) => row.id}
							itemContent={(_, row) => (
								<div
									data-flash={row.id === flashRowId || undefined}
									className="mx-auto max-w-3xl rounded-[var(--radius-sm)] px-md py-xs transition-colors data-[flash]:bg-primary-subtle"
								>
									<ChatTurnView
										row={row}
										projectAreaRoot={projectAreaRoot}
										onOpenChange={onOpenChange}
									/>
								</div>
							)}
						/>
						{showScrollButton ? (
							<button
								type="button"
								data-testid="scroll-to-bottom"
								onClick={scrollToBottom}
								className="-translate-x-1/2 absolute bottom-md left-1/2 flex items-center gap-xs rounded-[var(--radius-sm)] border border-border-default bg-container-elevated-bg px-sm py-xs text-text-muted tr-text-metadata shadow-[var(--shadow-md)] hover:bg-control-bg-hovered hover:text-text-default"
							>
								<ArrowDown className="size-3" />
								New messages
							</button>
						) : null}
					</div>
					{widgetEntries.length > 0 ? (
						<div className="shrink-0 border-border-default border-t bg-container-elevated-bg px-md py-xs text-text-muted tr-text-metadata">
							{widgetEntries.map(([key, lines]) => (
								<div key={key}>{lines.join(" ")}</div>
							))}
						</div>
					) : null}
					<QueueStrip queue={queue} onEdit={onEditQueued} onRemove={onRemoveQueued} />
					<div className="relative shrink-0">
						<HistoryOverlay
							state={historyState}
							projectAreaNames={projectAreaNames}
							onQueryChange={setQuery}
							onSetScope={setScope}
							onToggleStage={toggleStage}
							onMoveSelection={moveSelection}
							onClose={onDismissHistory}
							onInsert={onInsertHit}
							onInsertAndSend={onInsertAndSendHit}
							onOpenMessage={openMessage}
							onDeleteChat={(wsId, id) => void onDeleteHistoryChat(wsId, id)}
						/>
						<Composer
							ref={composerRef}
							value={draft}
							onChange={(v) => useAppStore.getState().setChatDraft(sessionId, v)}
							isStreaming={isStreaming}
							commands={mergedCommands}
							mentionCandidates={mentionCandidates}
							recentPrompts={recentPrompts}
							onMentionQuery={onMentionQuery}
							onSubmit={onSubmit}
							onAbort={onAbort}
							onHistoryOpen={onHistoryOpen}
						/>
					</div>
					{pendingExtUi ? (
						<ExtUiDialog key={pendingExtUi.id} request={pendingExtUi} onReply={onExtUiReply} />
					) : null}
				</div>
			</AskStatesContext.Provider>
		</ChatActionsContext.Provider>
	);
}

// gooseberry/webui/src/chat/chat-view.svelte
<script lang="ts">
import type {
	AgentMentionInfo,
	AskUserQuestionResult,
	PromptHit,
	QueueLane,
	WsResult,
} from "@gooseberry/contracts";
import { onDestroy, tick, untrack } from "svelte";
import Button from "../components/button.svelte";
import Dialog from "../components/dialog.svelte";
import { errorText, getTransport, wsErrorCode } from "../connection";
import {
	appStore,
	appStoreApi,
	type ChatLocationRequest,
	EMPTY_RUNTIME,
	selectProjectAreaById,
	toast,
} from "../store";
import {
	agentMentionIdentity,
	fileMentionCandidateIdentity,
	type LoadedAgentMentions,
	type LoadedFileMentionCandidates,
	visibleAgentMentions,
	visibleFileMentionCandidates,
} from "./composer/agent-mention-state";
import Composer from "./composer/composer.svelte";
import type { ComposerHandle, MentionCandidate, SubmitBehavior } from "./composer/composer-state";
import { loadTranscriptUntil, type TranscriptLoadOutcome } from "./history/history-loading";
import HistoryOverlay from "./history/history-overlay.svelte";
import {
	createHistorySearch,
	type HistorySearchState,
	type ScopeKind,
} from "./history/history-search";
import { deriveAskStates, setAskStatesContext } from "./runtime/ask-state";
import {
	messagesToRuntime,
	prependTranscriptPage as prependHydratedTranscriptPage,
} from "./runtime/hydrate";
import { deriveRows } from "./runtime/rows";
import type { ChatAttachment } from "./runtime/types";
import { setChatActionsContext } from "./session/chat-actions";
import ChatHeader from "./session/chat-header.svelte";
import QueueStrip from "./session/queue-strip.svelte";
import { createSessionCommandSync } from "./session/session-command-sync";
import SessionGoalControl from "./session/session-goal-control.svelte";
import { unsupportedLifecycleReason } from "./session/session-lifecycle";
import SessionLineageControl from "./session/session-lineage-control.svelte";
import SessionModeControl from "./session/session-mode-control.svelte";
import SessionModelControls from "./session/session-model-controls.svelte";
import SessionPlanControl from "./session/session-plan-control.svelte";
import { streamStatus } from "./session/stream-status";
import { setMcpAppSessionContext } from "./tools/apps/mcp-app-context";
import "./tools/register";
import type { ChatTranscriptHandle } from "./view/chat-transcript.svelte";
import ChatTranscript from "./view/chat-transcript.svelte";
import {
	locateChatRow,
	mentionCandidatesForQuery,
	projectAreaNameMap,
	resolveSendBehavior,
	uniqueRecentPrompts,
} from "./view/chat-view-state";

interface Props {
	sessionId: string;
	projectAreaId: string;
	onOpenChanges?: () => void;
}

type TranscriptLoadState = "idle" | "loading" | "error";
interface TranscriptLoadFlight {
	controller: AbortController;
	promise: Promise<TranscriptLoadOutcome>;
}
interface QueueEdit {
	lane: QueueLane;
	index: number;
	original: string;
	text: string;
	revision: string;
	saving: boolean;
	error: string | null;
}

let { sessionId, projectAreaId, onOpenChanges = () => {} }: Props = $props();
let composer = $state<ComposerHandle>();
let transcriptView = $state<ChatTranscriptHandle>();
let mentionQuery = $state<string | null>(null);
let loadedFileMentions = $state<LoadedFileMentionCandidates<MentionCandidate>>({
	identity: null,
	candidates: [],
});
let loadedAgentMentions = $state<LoadedAgentMentions>({ identity: null, mentions: [] });
let queueEdit = $state<QueueEdit | null>(null);
let queueEditor = $state<HTMLTextAreaElement>();
let queueEditorFocusKey = "";
let queueEditRequest = 0;
let transcriptLoadState = $state<TranscriptLoadState>("idle");
let transcriptFlight: TranscriptLoadFlight | null = null;
let flashRowId = $state<string | null>(null);
let chatLocationLoadRevision = $state(0);
let chatLocationLoad: {
	request: ChatLocationRequest;
	active: boolean;
	cursor: string;
} | null = null;

let runtime = $derived($appStore.sessions[sessionId] ?? EMPTY_RUNTIME);
let connectionGeneration = $derived($appStore.connectionGeneration);
let agentProfile = $derived($appStore.agentProfile);
let gooseAgent = $derived(agentProfile?.goose === true);
let isStreaming = $derived(runtime.isStreaming);
let canPromptImage = $derived(agentProfile ? agentProfile.operations.promptImage : null);
let canPromptEmbeddedContext = $derived(
	agentProfile ? agentProfile.operations.promptEmbeddedContext : null,
);
let canSteer = $derived(agentProfile?.operations.steer === true);
let canDelete = $derived(agentProfile?.operations.deleteSession === true);
let canUseHttpMcp = $derived(agentProfile?.operations.httpMcp === true);
let deleteUnavailableReason = $derived(
	canDelete ? undefined : unsupportedLifecycleReason(agentProfile?.name, "deleting"),
);
let projectId = $derived(
	Object.values($appStore.projectAreas)
		.flat()
		.find((area) => area.id === projectAreaId)?.projectId,
);
let projectAreaRoot = $derived(selectProjectAreaById($appStore, projectAreaId)?.root ?? undefined);
let projectAreaNames = $derived(projectAreaNameMap($appStore.projectAreas));
let parentDeleted = $derived(
	runtime.parentSessionId !== undefined &&
		$appStore.deletedSessionsByProjectArea[projectAreaId]?.[runtime.parentSessionId] === true,
);
let rows = $derived(deriveRows(runtime.turns, runtime.toolResults, runtime.isStreaming));
let recentPrompts = $derived(uniqueRecentPrompts(runtime.turns));
let headerStatusEntries = $derived(Object.entries(runtime.extUiStatus));
let projectionId = $derived(runtime.transcript?.projectionId ?? null);
let transcriptStart = $derived(runtime.transcript?.start ?? 0);
let conversationKey = $derived(projectionId ?? `live:${sessionId}`);
let currentStreamStatus = $derived(
	runtime.isStreaming && runtime.turns.at(-1)?.kind !== "retry"
		? streamStatus(runtime.turns, runtime.currentAssistantId)
		: null,
);
let permission = $derived(Object.values($appStore.pendingPermissions[sessionId] ?? {})[0] ?? null);
let fileMentionIdentity = $derived(
	fileMentionCandidateIdentity(projectAreaId, projectAreaRoot, sessionId, mentionQuery),
);
let fileMentions = $derived(visibleFileMentionCandidates(loadedFileMentions, fileMentionIdentity));
let agentIdentity = $derived(agentMentionIdentity(projectId, sessionId));
let agentMentions = $derived(visibleAgentMentions(loadedAgentMentions, agentIdentity));
let mentionCandidates = $derived(
	mentionCandidatesForQuery(mentionQuery, agentMentions, fileMentions),
);
let queueEditStale = $derived(
	queueEdit !== null && !queueEdit.saving && queueEdit.revision !== runtime.queue.revision,
);
let askStates = $derived(deriveAskStates(runtime.turns, runtime.askAnswers));
function currentHistoryContext() {
	return {
		sessionId,
		projectAreaId,
		...(projectId === undefined ? {} : { projectId }),
	};
}

const focusScope = {};
const history = createHistorySearch(untrack(currentHistoryContext));
let historyState = $state<HistorySearchState>(history.getState());
const unsubscribeHistory = history.subscribe((next) => (historyState = next));
const commandSync = createSessionCommandSync(untrack(() => ({ sessionId, projectAreaId })));

setAskStatesContext({ stateFor: (toolCallId) => askStates[toolCallId], focusScope });
setChatActionsContext({
	answerQuestion: async (toolCallId: string, result: AskUserQuestionResult) => {
		try {
			await getTransport().request("session.questionReply", { sessionId, toolCallId, result });
			appStoreApi.getState().setAskAnswer(sessionId, toolCallId, result);
		} catch (cause) {
			toast.error(errorText(cause), "Couldn't send the answer");
			throw cause;
		}
	},
	focusComposer: () => composer?.refocus(),
});
setMcpAppSessionContext({
	get projectId() {
		return projectId;
	},
	get sessionId() {
		return sessionId;
	},
});

onDestroy(() => {
	transcriptFlight?.controller.abort();
	transcriptFlight = null;
	unsubscribeHistory();
	history.destroy();
	commandSync.destroy();
});

$effect(() => {
	history.setContext(currentHistoryContext());
	commandSync.setContext({ sessionId, projectAreaId });
});

$effect(() => {
	const generation = connectionGeneration;
	const projection = projectionId;
	const activeSessionId = sessionId;
	void generation;
	void projection;
	void activeSessionId;
	transcriptLoadState = "idle";
	return () => {
		const flight = transcriptFlight;
		if (!flight) return;
		transcriptFlight = null;
		flight.controller.abort();
	};
});

$effect(() => {
	const id = sessionId;
	const streaming = isStreaming;
	void streaming;
	void getTransport()
		.request("session.getStats", { sessionId: id })
		.then((stats) => appStoreApi.getState().setStats(id, stats))
		.catch(() => {});
});

$effect(() => {
	const identity = agentIdentity;
	const id = sessionId;
	const activeProjectId = projectId;
	loadedAgentMentions = { identity, mentions: [] };
	if (!gooseAgent || !activeProjectId || !identity) return;
	let cancelled = false;
	void getTransport()
		.request("session.getAgentMentions", { projectId: activeProjectId, sessionId: id })
		.then((mentions: AgentMentionInfo[]) => {
			if (!cancelled) loadedAgentMentions = { identity, mentions };
		})
		.catch(() => {
			if (!cancelled) loadedAgentMentions = { identity, mentions: [] };
		});
	return () => {
		cancelled = true;
	};
});

$effect(() => {
	const query = mentionQuery;
	const identity = fileMentionIdentity;
	loadedFileMentions = { identity, candidates: [] };
	if (query === null || !identity) return;
	const slash = query.lastIndexOf("/");
	const dir = slash >= 0 ? query.slice(0, slash) : "";
	const prefix = (slash >= 0 ? query.slice(slash + 1) : query).toLocaleLowerCase();
	let cancelled = false;
	const timer = setTimeout(() => {
		void getTransport()
			.request("fs.readDir", { projectId: projectAreaId, path: dir })
			.then(({ nodes }) => {
				if (cancelled) return;
				loadedFileMentions = {
					identity,
					candidates: nodes
						.filter((node) => node.name.toLocaleLowerCase().startsWith(prefix))
						.slice(0, 12)
						.map((node) => ({ path: node.path, name: node.name, kind: node.kind })),
				};
			})
			.catch(() => {
				if (!cancelled) loadedFileMentions = { identity, candidates: [] };
			});
	}, 120);
	return () => {
		cancelled = true;
		clearTimeout(timer);
	};
});

$effect(() => {
	const request = $appStore.historyOpenRequest;
	const open = historyState.open;
	if (request?.sessionId !== sessionId) return;
	if (appStoreApi.getState().historyOpenRequest !== request) return;
	appStoreApi.getState().clearHistoryOpen();
	if (open) history.cycleScope();
	else composer?.openHistory();
});

$effect(() => {
	const rowId = flashRowId;
	if (rowId === null) return;
	const timer = setTimeout(() => {
		if (flashRowId === rowId) flashRowId = null;
	}, 1600);
	return () => clearTimeout(timer);
});

$effect(() => {
	const key = queueEdit ? `${queueEdit.lane}:${queueEdit.index}:${queueEdit.revision}` : "";
	const editor = queueEditor;
	if (!key) {
		queueEditorFocusKey = "";
		return;
	}
	if (!editor || key === queueEditorFocusKey) return;
	queueEditorFocusKey = key;
	queueMicrotask(() => {
		if (editor.isConnected) editor.focus();
	});
});

function loadEarlierMessages(): Promise<TranscriptLoadOutcome> {
	if (transcriptFlight) return transcriptFlight.promise;
	const state = appStoreApi.getState();
	const transcript = state.sessions[sessionId]?.transcript;
	if (!transcript || transcript.start <= 0) return Promise.resolve("exhausted");
	if (state.status !== "connected") {
		transcriptLoadState = "error";
		return Promise.resolve("failed");
	}

	const generation = state.connectionGeneration;
	const before = transcript.start;
	const expectedProjectionId = transcript.projectionId;
	const controller = new AbortController();
	const anchor = transcriptView?.beginPrepend() ?? null;
	const flight: TranscriptLoadFlight = {
		controller,
		promise: Promise.resolve("ignored"),
	};
	const isCurrent = () => transcriptFlight === flight;
	const isSameRuntime = () => {
		const current = appStoreApi.getState();
		const currentTranscript = current.sessions[sessionId]?.transcript;
		return (
			current.status === "connected" &&
			current.connectionGeneration === generation &&
			currentTranscript?.projectionId === expectedProjectionId &&
			currentTranscript.start === before
		);
	};
	transcriptLoadState = "loading";
	flight.promise = (async (): Promise<TranscriptLoadOutcome> => {
		let restoreAnchor = false;
		let resetToBottom = false;
		try {
			let response: WsResult<"session.getMessages">;
			try {
				response = await getTransport().request(
					"session.getMessages",
					{
						sessionId,
						projectId: projectAreaId,
						before: { projectionId: expectedProjectionId, index: before },
					},
					{ signal: controller.signal },
				);
			} catch (cause) {
				if (wsErrorCode(cause) !== "STALE_TRANSCRIPT_PROJECTION") throw cause;
				if (!isSameRuntime()) return "ignored";
				const snapshot = await getTransport().request(
					"session.getMessages",
					{ sessionId, projectId: projectAreaId },
					{ signal: controller.signal },
				);
				if (snapshot.kind !== "snapshot") throw new Error("invalid chat snapshot");
				if (!isSameRuntime()) return "ignored";
				const hydrated = messagesToRuntime(snapshot.messages, {
					lastSettlement: snapshot.summary.lastSettlement,
					pendingTools: snapshot.pendingTools,
					page: snapshot.page,
					isStreaming: snapshot.summary.isStreaming,
				});
				appStoreApi
					.getState()
					.replaceTranscriptSnapshot(
						sessionId,
						snapshot.summary,
						hydrated,
						snapshot.modes,
						snapshot.planState,
					);
				appStoreApi.getState().setCommands(sessionId, snapshot.commands);
				if (isCurrent()) transcriptLoadState = "idle";
				resetToBottom = true;
				return "reloaded";
			}

			if (response.kind !== "page") throw new Error("invalid transcript page");
			if (!isSameRuntime()) return "ignored";
			const hydrated = messagesToRuntime(response.messages, { page: response.page });
			const currentRuntime = appStoreApi.getState().sessions[sessionId];
			if (!currentRuntime || !prependHydratedTranscriptPage(currentRuntime, hydrated)) {
				return "ignored";
			}
			const applied = appStoreApi.getState().prependTranscriptPage(sessionId, hydrated);
			if (!applied) return "ignored";
			restoreAnchor = true;
			if (isCurrent()) transcriptLoadState = "idle";
			return "loaded";
		} catch (cause) {
			if ((cause as { name?: string }).name === "AbortError") return "ignored";
			if (isCurrent()) transcriptLoadState = "error";
			return "failed";
		} finally {
			if (isCurrent()) transcriptFlight = null;
			await transcriptView?.finishPrepend(anchor, restoreAnchor);
			if (resetToBottom) transcriptView?.scrollToBottom("auto");
		}
	})();
	transcriptFlight = flight;
	return flight.promise;
}

function respondToPermission(optionId?: string): void {
	const request = permission;
	if (!request) return;
	void getTransport()
		.request("session.permissionReply", {
			sessionId,
			permissionId: request.id,
			...(optionId === undefined ? {} : { optionId }),
		})
		.then(() => appStoreApi.getState().clearPendingPermission(sessionId, request.id))
		.catch((cause) => {
			toast.error(errorText(cause), "Couldn't send permission decision");
			appStoreApi.getState().clearPendingPermission(sessionId, request.id);
		});
}

function restoreTextToDraft(text: string): void {
	if (!text.trim()) return;
	const current = appStoreApi.getState().sessions[sessionId]?.draft ?? "";
	appStoreApi
		.getState()
		.setChatDraft(sessionId, [text, current].filter((part) => part.trim()).join("\n\n"));
	composer?.refocus();
}

function performSend(
	text: string,
	attachments: ChatAttachment[],
	behavior: Exclude<SubmitBehavior, "interrupt">,
): boolean {
	const { effectiveBehavior, heldByQueue } = resolveSendBehavior(
		behavior,
		canSteer,
		runtime.queue.followUp.length > 0,
	);
	const images = attachments.flatMap((attachment) =>
		attachment.kind === "image" ? [attachment.content] : [],
	);
	const resources = attachments.flatMap((attachment) =>
		attachment.kind === "text" ? [attachment.content] : [],
	);
	if (canPromptImage === false && images.length > 0) {
		toast.error(`${agentProfile?.name || "The connected agent"} does not support image prompts.`);
		return false;
	}
	if (canPromptEmbeddedContext === false && resources.length > 0) {
		toast.error(
			`${agentProfile?.name || "The connected agent"} does not support text resource prompts.`,
		);
		return false;
	}
	if (effectiveBehavior === "queue" && attachments.length > 0) {
		toast.error(
			heldByQueue
				? "Resolve the queued follow-ups before sending images."
				: canSteer
					? "Send or steer image attachments directly."
					: "Wait for the current response, then send image attachments directly.",
			"Queued messages are text-only",
		);
		return false;
	}
	if (heldByQueue) toast.info("Queued behind the existing follow-ups.", "Message queued");
	if (effectiveBehavior === "send" && (text || attachments.length > 0)) {
		appStoreApi.getState().appendUserMessage(sessionId, text, attachments);
	}
	const params = {
		sessionId,
		text,
		...(images.length > 0 ? { images } : {}),
		...(resources.length > 0 ? { resources } : {}),
	};
	const method =
		effectiveBehavior === "steer"
			? "session.steer"
			: effectiveBehavior === "queue"
				? "session.queueAdd"
				: "session.prompt";
	void getTransport()
		.request(method, params)
		.catch((cause) => {
			appStoreApi.getState().appendErrorTurn(sessionId, errorText(cause));
			if (effectiveBehavior !== "send") restoreTextToDraft(text);
		});
	return true;
}

function submit(text: string, attachments: ChatAttachment[], behavior: SubmitBehavior): boolean {
	if (behavior !== "interrupt") return performSend(text, attachments, behavior);
	void getTransport()
		.request("session.abort", { sessionId })
		.then(() => performSend(text, attachments, "send"))
		.catch((cause) => {
			appStoreApi.getState().appendErrorTurn(sessionId, errorText(cause));
			restoreTextToDraft(text);
		});
	return true;
}

function editQueuedMessage(lane: QueueLane, index: number): void {
	const current = runtime.queue[lane][index];
	const revision = runtime.queue.revision;
	if (!current || !revision) return;
	queueEditRequest += 1;
	queueEdit = {
		lane,
		index,
		original: current,
		text: current,
		revision,
		saving: false,
		error: null,
	};
}

function dismissQueueEdit(): void {
	queueEditRequest += 1;
	queueEdit = null;
}

function saveQueuedMessage(): void {
	const edit = queueEdit;
	if (!edit || edit.saving || queueEditStale) return;
	const text = edit.text.trim();
	if (!text || text === edit.original) {
		dismissQueueEdit();
		return;
	}
	const request = ++queueEditRequest;
	queueEdit = { ...edit, saving: true, error: null };
	void getTransport()
		.request("session.queueEdit", {
			sessionId,
			lane: edit.lane,
			index: edit.index,
			text,
			revision: edit.revision,
		})
		.then(() => {
			if (queueEditRequest === request) queueEdit = null;
		})
		.catch((cause) => {
			if (queueEditRequest === request && queueEdit) {
				queueEdit = { ...queueEdit, saving: false, error: errorText(cause) };
			}
		});
}

function removeQueuedMessage(lane: QueueLane, index: number): void {
	const revision = runtime.queue.revision;
	if (!revision) return;
	void getTransport()
		.request("session.queueRemove", { sessionId, lane, index, revision })
		.catch((cause) => toast.error(errorText(cause), "Couldn't remove queued message"));
}

function retryQueuedMessage(lane: QueueLane, index: number): void {
	const revision = runtime.queue.revision;
	if (!revision) return;
	void getTransport()
		.request("session.queueRetry", { sessionId, lane, index, revision })
		.catch((cause) => toast.error(errorText(cause), "Couldn't retry queued message"));
}

function dismissHistory(): void {
	history.close();
	composer?.refocus();
}

function insertHistoryHit(hit: PromptHit): void {
	composer?.insertText(hit.text);
	history.close();
}

function insertAndSendHistoryHit(hit: PromptHit): void {
	composer?.insertAndSubmit(
		hit.text,
		runtime.isStreaming ? (canSteer ? "steer" : "queue") : "send",
	);
	history.close();
}

async function deleteHistoryChat(targetProjectAreaId: string, targetSessionId: string) {
	if (!canDelete) return;
	try {
		await getTransport().request("session.delete", {
			projectId: targetProjectAreaId,
			sessionId: targetSessionId,
		});
		history.close();
		appStoreApi.getState().deleteChat(targetProjectAreaId, targetSessionId);
	} catch (cause) {
		toast.error(errorText(cause), "Couldn't delete the chat");
	}
}

function revealLocation(request: ChatLocationRequest, rowId: string): void {
	void tick().then(() => {
		if (appStoreApi.getState().chatLocationRequest !== request) return;
		if (!transcriptView?.scrollToRow(rowId)) {
			toast.error("couldn't locate the message — the session may have changed");
			appStoreApi.getState().clearChatLocation();
			return;
		}
		flashRowId = rowId;
		appStoreApi.getState().clearChatLocation();
	});
}

$effect(() => {
	const request = $appStore.chatLocationRequest;
	const revision = chatLocationLoadRevision;
	const transcript = runtime.transcript;
	const currentRows = rows;
	void revision;
	if (
		!request ||
		request.projectAreaId !== projectAreaId ||
		request.sessionId !== sessionId ||
		appStoreApi.getState().chatLocationRequest !== request
	) {
		return;
	}
	if (transcript && request.messageIndex < transcript.start) {
		const cursor = `${transcript.projectionId}:${transcript.start}`;
		if (
			chatLocationLoad?.request === request &&
			(chatLocationLoad.active || chatLocationLoad.cursor === cursor)
		) {
			return;
		}
		const load = { request, active: true, cursor };
		chatLocationLoad = load;
		void loadTranscriptUntil(
			request.messageIndex,
			() => appStoreApi.getState().sessions[sessionId]?.transcript,
			loadEarlierMessages,
			() => appStoreApi.getState().chatLocationRequest === request,
		).finally(() => {
			if (chatLocationLoad !== load) return;
			const latest = appStoreApi.getState().sessions[sessionId]?.transcript;
			chatLocationLoad = {
				...load,
				active: false,
				cursor: latest ? `${latest.projectionId}:${latest.start}` : "",
			};
			chatLocationLoadRevision += 1;
		});
		return;
	}
	const row = locateChatRow(
		request.messageIndex,
		request.anchorText,
		runtime.turnIdByMessageIndex,
		runtime.turns,
		currentRows,
	);
	if (!row) {
		toast.error("couldn't locate the message — the session may have changed");
		appStoreApi.getState().clearChatLocation();
		return;
	}
	revealLocation(request, row.id);
});

function openChanges(path: string): void {
	appStoreApi.getState().requestChangesView(projectAreaId, path);
	onOpenChanges();
}
</script>

{#snippet HeaderLeft()}
	<div class="flex min-w-0 flex-wrap items-center gap-xs">
		{#if gooseAgent}
			<SessionModelControls
				sessionId={sessionId}
				model={runtime.model}
				thinkingLevel={runtime.thinkingLevel}
				isStreaming={runtime.isStreaming}
			/>
		{/if}
		<SessionLineageControl
			projectAreaId={projectAreaId}
			parentSessionId={runtime.parentSessionId}
			{parentDeleted}
		/>
		<SessionGoalControl
			projectAreaId={projectAreaId}
			{sessionId}
			agentCanAccessGoal={canUseHttpMcp}
			agentName={agentProfile?.name}
		/>
		<SessionPlanControl planState={runtime.planState} />
		<SessionModeControl {sessionId} modes={runtime.modes} />
	</div>
{/snippet}

<div class="flex h-full min-h-0 flex-col bg-container-project-bg">
	{#if permission}
		<Dialog
			open
			title={`Allow ${permission.title}?`}
			description="Choose how the agent may continue with this tool request."
			role="alertdialog"
			testid="tool-permission-dialog"
			onOpenChange={(open) => {
				if (!open) respondToPermission();
			}}
		>
			<div class="flex flex-wrap gap-xs">
				{#each permission.options as option (option.optionId)}
					<Button
						variant="outline"
						onclick={() => respondToPermission(option.optionId)}
					>
						{option.name} ({option.kind})
					</Button>
				{/each}
			</div>
		</Dialog>
	{/if}

	<ChatTranscript
		bind:this={transcriptView}
		{rows}
		{conversationKey}
		{projectAreaRoot}
		{flashRowId}
		status={currentStreamStatus}
		{transcriptStart}
		loadState={transcriptLoadState}
		onLoadEarlier={() => void loadEarlierMessages()}
		onOpenChange={openChanges}
	/>

	<div class="relative shrink-0">
		<HistoryOverlay
			state={historyState}
			{projectAreaNames}
			onQueryChange={(query) => history.setQuery(query)}
			onSetScope={(scope: ScopeKind) => history.setScope(scope)}
			onToggleStage={() => history.toggleStage()}
			onMoveSelection={(delta) => history.moveSelection(delta)}
			onClose={dismissHistory}
			onInsert={insertHistoryHit}
			onInsertAndSend={insertAndSendHistoryHit}
			onOpenMessage={(request) => history.openMessage(request)}
			onDeleteChat={(targetProjectAreaId, targetSessionId) =>
				void deleteHistoryChat(targetProjectAreaId, targetSessionId)}
			{deleteUnavailableReason}
		/>
		<QueueStrip
			queue={runtime.queue}
			onEdit={editQueuedMessage}
			onRemove={removeQueuedMessage}
			onRetry={retryQueuedMessage}
		/>
		{#if queueEdit}
			{@const activeQueueEdit = queueEdit}
			<Dialog
				open
				title="Edit queued message"
				description={runtime.queue.blocked?.lane === activeQueueEdit.lane &&
				runtime.queue.blocked.index === activeQueueEdit.index
					? "This may already be in the transcript. Editing changes the text used if you retry it."
					: "Update the text that the agent will receive later."}
				onOpenChange={(open) => {
					if (!open) dismissQueueEdit();
				}}
			>
				{#snippet actions()}
					<Button variant="ghost" onclick={dismissQueueEdit}>Cancel</Button>
					<Button
						disabled={!activeQueueEdit.text.trim() || activeQueueEdit.saving || queueEditStale}
						onclick={saveQueuedMessage}
					>
						{activeQueueEdit.saving ? "Saving…" : "Save"}
					</Button>
				{/snippet}
				<textarea
					bind:this={queueEditor}
					aria-label="Queued message"
					value={activeQueueEdit.text}
					disabled={activeQueueEdit.saving}
					oninput={(event) => {
						if (queueEdit) queueEdit = { ...queueEdit, text: event.currentTarget.value };
					}}
					class="input min-h-28 w-full resize-y"
				></textarea>
				{#if queueEditStale || activeQueueEdit.error}
					<p role="alert" class="text-feedback-warning tr-text-ui">
						{queueEditStale
							? "The queue changed while you were editing. Copy your draft, then reopen the message to edit its current version."
							: `${activeQueueEdit.error} Your draft is still here.`}
					</p>
				{/if}
			</Dialog>
		{/if}
		<Composer
			bind:this={composer}
			value={runtime.draft}
			onChange={(value) => appStoreApi.getState().setChatDraft(sessionId, value)}
			isStreaming={runtime.isStreaming}
			commands={runtime.commands}
			{mentionCandidates}
			{recentPrompts}
			onMentionQuery={(query) => (mentionQuery = query)}
			onSubmit={submit}
			onAbort={() => void getTransport().request("session.abort", { sessionId }).catch(() => {})}
			onHistoryOpen={() => history.openOverlay(runtime.draft)}
			supportsImages={canPromptImage}
			supportsTextResources={canPromptEmbeddedContext}
			supportsSteer={canSteer}
		/>
		<ChatHeader stats={runtime.stats} statusEntries={headerStatusEntries} left={HeaderLeft} />
	</div>
</div>
