// gooseberry/webui/src/chat/composer/composer.svelte
<script module lang="ts">
export type {
	ComposerHandle,
	ComposerProps,
	MentionCandidate,
	SubmitBehavior,
} from "./composer-state";
</script>

<script lang="ts">
	import {
		ACCEPTED_IMAGE_TYPES,
		ACCEPTED_TEXT_ATTACHMENT_EXTENSIONS,
		REQUEST_IMAGE_BASE64_BUDGET,
		utf8ByteLength,
		validateTextResourceAttachments,
	} from "@gooseberry/contracts";
	import { tick, untrack } from "svelte";
	import { mewa } from "../../../vendor/mewa-svelte/index.js";
	import { behavior as dropdownBehavior } from "../../../vendor/mewa-ui/components/dropdown-menu.js";
	import Button from "../../components/button.svelte";
	import Icon from "../../components/icon.svelte";
	import { randomId } from "../../lib";
	import type { ChatAttachment } from "../runtime/types";
	import {
		activeToken,
		agentMentionLabel,
		agentMentionSummary,
		clampedMentionActiveIndex,
		composerEnterBehavior,
		imageAttachmentTag,
		insertedMention,
		insertImageTags,
		mentionCompletionKeyAction,
		removeImageTags,
		reserveClipboardImageNames,
		streamingSendModes,
		streamingSubmitBehavior,
		type ComposerProps,
		type MentionCandidate,
		type SubmitBehavior,
	} from "./composer-state";
	import FileChip from "./file-chip.svelte";
	import { type AttachedImage, fileToAttachedImage } from "./image-attachment";
	import {
		clampedSlashActiveIndex,
		matchSlashCommands,
		selectedSlashCommandValue,
		slashCommandQuery,
		slashCommandResetSignal,
		slashCompletionKeyAction,
	} from "./slash-command-completion";
	import SlashCommandMenu from "./slash-command-menu.svelte";
	import { fileToTextResource } from "./text-attachment";

	interface PendingImage extends AttachedImage {
		id: string;
		name: string;
		tag?: string;
	}

	interface PendingText {
		id: string;
		name: string;
		content: Extract<ChatAttachment, { kind: "text" }>["content"];
	}

	interface AttachError {
		id: string;
		name: string;
		reason: string;
	}

	let {
		value,
		onChange,
		isStreaming,
		commands,
		mentionCandidates,
		recentPrompts,
		onMentionQuery,
		onSubmit,
		onAbort,
		onHistoryOpen,
		supportsImages = true,
		supportsTextResources = true,
		supportsSteer = true,
	}: ComposerProps = $props();

	let textarea = $state<HTMLTextAreaElement>();
	let fileInput = $state<HTMLInputElement>();
	let sendMenu = $state<HTMLElement>();
	let caret = $state(untrack(() => value.length));
	let images = $state<PendingImage[]>([]);
	let texts = $state<PendingText[]>([]);
	let pendingAttachments = $state(0);
	let attachErrors = $state<AttachError[]>([]);
	let mentionActiveIndex = $state(0);
	let mentionDismissed = $state(false);
	let slashActiveIndex = $state(0);
	let slashDismissed = $state(false);
	let recalledPromptIndex: number | null = null;
	let draftSnapshot = untrack(() => value);
	let reservedImageNames: string[] = [];
	let selectionRevision = 0;
	let previousMentionQuery: string | null | undefined;
	let previousSlashSignal = "";
	let previousSupportsImages = untrack(() => supportsImages);
	let previousSupportsTextResources = untrack(() => supportsTextResources);

	const componentId = $props.id();
	const mentionListboxId = `composer-mentions-${componentId}`;
	const slashListboxId = `composer-slash-${componentId}`;
	const sendMenuId = `composer-send-${componentId}`;
	const inputId = `composer-input-${componentId}`;

	let tokenState = $derived(activeToken(value, caret));
	let mentionQuery = $derived(tokenState.token.startsWith("@") ? tokenState.token.slice(1) : null);
	let mentionOpen = $derived(
		!mentionDismissed && mentionQuery !== null && mentionCandidates.length > 0,
	);
	let visibleMentionActiveIndex = $derived(
		clampedMentionActiveIndex(mentionActiveIndex, mentionCandidates.length),
	);
	let slashQuery = $derived(slashCommandQuery(value));
	let slashMatches = $derived(matchSlashCommands(value, commands));
	let slashSignal = $derived(slashCommandResetSignal(value, commands));
	let slashOpen = $derived(!slashDismissed && slashQuery !== null && slashMatches.length > 0);
	let visibleSlashActiveIndex = $derived(
		clampedSlashActiveIndex(slashActiveIndex, slashMatches.length),
	);
	let completionOpen = $derived(mentionOpen || slashOpen);
	let completionListboxId = $derived(mentionOpen ? mentionListboxId : slashListboxId);
	let activeCompletionId = $derived(
		mentionOpen
			? `${mentionListboxId}-option-${visibleMentionActiveIndex}`
			: slashOpen
				? `${slashListboxId}-option-${visibleSlashActiveIndex}`
				: undefined,
	);
	let imagePromptsEnabled = $derived(supportsImages !== false);
	let textResourcesEnabled = $derived(supportsTextResources !== false);
	let attachmentPromptsEnabled = $derived(imagePromptsEnabled || textResourcesEnabled);
	let acceptedAttachments = $derived(
		[
			...ACCEPTED_IMAGE_TYPES,
			...ACCEPTED_TEXT_ATTACHMENT_EXTENSIONS.map((extension) => `.${extension}`),
		].join(","),
	);
	let placeholder = $derived(
		isStreaming
			? supportsSteer
				? "Enter steers at the next step · Cmd/Ctrl+Enter queues for when it finishes"
				: "Enter queues a follow-up for when the agent finishes"
			: "Message the agent…  (@ files · / commands · Enter to send)",
	);

	$effect(() => {
		draftSnapshot = value;
	});

	$effect(() => {
		const query = mentionQuery;
		onMentionQuery(query);
		if (query !== previousMentionQuery) {
			previousMentionQuery = query;
			mentionActiveIndex = 0;
			mentionDismissed = false;
		}
	});

	$effect(() => {
		const signal = slashSignal;
		if (signal !== previousSlashSignal) {
			previousSlashSignal = signal;
			slashActiveIndex = 0;
			slashDismissed = false;
		}
	});

	$effect(() => {
		const support = supportsImages;
		if (support === false && previousSupportsImages !== false && images.length > 0) {
			images = [];
			attachErrors = [
				{
					id: randomId(),
					name: "images",
					reason: "connected agent does not support image prompts",
				},
			];
		}
		previousSupportsImages = support;
	});

	$effect(() => {
		const support = supportsTextResources;
		if (support === false && previousSupportsTextResources !== false && texts.length > 0) {
			texts = [];
			attachErrors = [
				{
					id: randomId(),
					name: "text files",
					reason: "connected agent does not support text resource prompts",
				},
			];
		}
		previousSupportsTextResources = support;
	});

	function commitImages(next: PendingImage[]): void {
		images = next;
	}

	function commitTexts(next: PendingText[]): void {
		texts = next;
	}

	function focusSelection(start: number, end = start): void {
		caret = start;
		const revision = ++selectionRevision;
		void tick().then(() => {
			if (revision !== selectionRevision || !textarea) return;
			textarea.focus();
			textarea.setSelectionRange(start, end);
			caret = textarea.selectionStart;
		});
	}

	function replaceDraft(text: string, nextCaret = text.length): void {
		recalledPromptIndex = null;
		draftSnapshot = text;
		onChange(text);
		focusSelection(nextCaret);
	}

	function canSubmit(raw: string): boolean {
		return (
			pendingAttachments === 0 &&
			(!!raw.trim() ||
				(imagePromptsEnabled && images.length > 0) ||
				(textResourcesEnabled && texts.length > 0))
		);
	}

	function submitText(raw: string, behavior: SubmitBehavior): void {
		if (!canSubmit(raw)) return;
		const accepted = onSubmit(
			raw.trim(),
			[
				...(imagePromptsEnabled
					? images.map(({ name, content }) => ({ kind: "image" as const, name, content }))
					: []),
				...(textResourcesEnabled
					? texts.map(({ name, content }) => ({ kind: "text" as const, name, content }))
					: []),
			],
			behavior,
		);
		if (accepted === false) return;
		draftSnapshot = "";
		caret = 0;
		onChange("");
		commitImages([]);
		commitTexts([]);
		attachErrors = [];
		recalledPromptIndex = null;
	}

	function pickMention(candidate: MentionCandidate): void {
		const before = value.slice(0, tokenState.start);
		const after = value.slice(caret);
		const insert = insertedMention(candidate);
		const suffix = candidate.kind === "dir" ? "" : " ";
		replaceDraft(
			`${before}${insert}${suffix}${after}`,
			before.length + insert.length + suffix.length,
		);
	}

	function dismissSlashCompletion(): void {
		slashDismissed = true;
	}

	function pickSlashCommand(command: Parameters<typeof selectedSlashCommandValue>[0]): void {
		replaceDraft(selectedSlashCommandValue(command));
		dismissSlashCompletion();
	}

	export function openHistory(): void {
		mentionDismissed = true;
		dismissSlashCompletion();
		onHistoryOpen?.();
	}

	export function insertText(text: string): void {
		replaceDraft(text);
	}

	export function insertAndSubmit(text: string, behavior: SubmitBehavior): void {
		if (canSubmit(text)) submitText(text, behavior);
		else replaceDraft(text);
	}

	export function refocus(): void {
		focusSelection(caret);
	}

	async function addFiles(files: File[], pastedImageNames?: readonly string[]): Promise<void> {
		const imageFiles = files.filter((file) => file.type.startsWith("image/"));
		const textFiles = files.filter(
			(file) => !file.type.startsWith("image/") && file.name.includes("."),
		);
		const unsupported = files.filter(
			(file) => !imageFiles.includes(file) && !textFiles.includes(file),
		);
		if (files.length === 0) return;

		pendingAttachments += files.length;
		try {
			const [imageResults, textResults] = await Promise.all([
				Promise.allSettled(imageFiles.map(fileToAttachedImage)),
				Promise.allSettled(textFiles.map(fileToTextResource)),
			]);
			let used = images.reduce((sum, pending) => sum + pending.content.data.length, 0);
			const imageAdditions: PendingImage[] = [];
			const textAdditions: PendingText[] = [];
			const errors: AttachError[] = [];
			const failedImageNames: string[] = [];

			imageResults.forEach((result, index) => {
				const file = imageFiles[index];
				const name = pastedImageNames?.[index] ?? file?.name ?? "image";
				if (supportsImages === false) {
					errors.push({
						id: randomId(),
						name,
						reason: "connected agent does not support image prompts",
					});
					if (pastedImageNames) failedImageNames.push(name);
					return;
				}
				if (result.status !== "fulfilled" || result.value === null) {
					errors.push({ id: randomId(), name, reason: "unsupported image format" });
					if (pastedImageNames) failedImageNames.push(name);
					return;
				}
				const size = result.value.content.data.length;
				if (used + size > REQUEST_IMAGE_BASE64_BUDGET) {
					errors.push({ id: randomId(), name, reason: "message image limit reached" });
					if (pastedImageNames) failedImageNames.push(name);
					return;
				}
				used += size;
				imageAdditions.push({
					id: randomId(),
					name,
					...(pastedImageNames ? { tag: imageAttachmentTag(name) } : {}),
					...result.value,
				});
			});

			textResults.forEach((result, index) => {
				const name = textFiles[index]?.name ?? "file";
				if (supportsTextResources === false) {
					errors.push({
						id: randomId(),
						name,
						reason: "connected agent does not support text resource prompts",
					});
					return;
				}
				if (result.status !== "fulfilled") {
					errors.push({
						id: randomId(),
						name,
						reason:
							result.reason instanceof Error
								? result.reason.message
								: "unsupported text file",
					});
					return;
				}
				try {
					validateTextResourceAttachments([
						...texts.map((attachment) => attachment.content),
						...textAdditions.map((attachment) => attachment.content),
						result.value,
					]);
				} catch (error) {
					errors.push({
						id: randomId(),
						name,
						reason:
							error instanceof Error
								? error.message
								: "message text attachment limit reached",
					});
					return;
				}
				textAdditions.push({ id: randomId(), name, content: result.value });
			});

			unsupported.forEach((file) => {
				errors.push({
					id: randomId(),
					name: file.name || "file",
					reason: "supported image or text file required",
				});
			});

			if (supportsImages !== false && imageAdditions.length > 0) {
				commitImages([...images, ...imageAdditions]);
			}
			if (failedImageNames.length > 0) {
				const removal = removeImageTags(draftSnapshot, caret, failedImageNames);
				replaceDraft(removal.value, removal.caret);
			}
			if (supportsTextResources !== false && textAdditions.length > 0) {
				commitTexts([...texts, ...textAdditions]);
			}
			if (errors.length > 0) attachErrors = [...attachErrors, ...errors];
		} finally {
			if (pastedImageNames) {
				reservedImageNames = reservedImageNames.filter(
					(name) => !pastedImageNames.includes(name),
				);
			}
			pendingAttachments -= files.length;
		}
	}

	function removeImage(image: PendingImage): void {
		commitImages(images.filter((current) => current.id !== image.id));
		if (!image.tag) return;
		const removal = removeImageTags(draftSnapshot, caret, [image.name]);
		if (removal.value !== draftSnapshot) replaceDraft(removal.value, removal.caret);
	}

	function handleSlashKeyDown(event: KeyboardEvent): boolean {
		const action = slashCompletionKeyAction(
			event.key,
			slashOpen,
			visibleSlashActiveIndex,
			slashMatches.length,
		);
		if (action.type === "none") return false;
		event.preventDefault();
		event.stopPropagation();
		if (action.type === "move") slashActiveIndex = action.index;
		if (action.type === "dismiss") dismissSlashCompletion();
		if (action.type === "select") {
			const command = slashMatches[action.index];
			if (command) pickSlashCommand(command);
		}
		return true;
	}

	function handleKeyDown(event: KeyboardEvent): void {
		if (event.isComposing || event.keyCode === 229) return;
		if (mentionOpen) {
			const action = mentionCompletionKeyAction(
				event.key,
				mentionOpen,
				visibleMentionActiveIndex,
				mentionCandidates.length,
			);
			if (action.type !== "none") {
				event.preventDefault();
				event.stopPropagation();
				if (action.type === "move") mentionActiveIndex = action.index;
				if (action.type === "dismiss") mentionDismissed = true;
				if (action.type === "select") {
					const candidate = mentionCandidates[action.index];
					if (candidate) pickMention(candidate);
				}
				return;
			}
		}
		if (handleSlashKeyDown(event)) return;

		const recallAt = recalledPromptIndex;
		if (event.key === "ArrowUp" && (value === "" || recallAt !== null) && recentPrompts.length > 0) {
			event.preventDefault();
			const next = recallAt === null ? 0 : Math.min(recallAt + 1, recentPrompts.length - 1);
			const text = recentPrompts[next] ?? "";
			recalledPromptIndex = next;
			draftSnapshot = text;
			onChange(text);
			focusSelection(text.length);
			return;
		}
		if (event.key === "ArrowDown" && recallAt !== null) {
			event.preventDefault();
			if (recallAt === 0) {
				recalledPromptIndex = null;
				draftSnapshot = "";
				onChange("");
				focusSelection(0);
			} else {
				const next = recallAt - 1;
				const text = recentPrompts[next] ?? "";
				recalledPromptIndex = next;
				draftSnapshot = text;
				onChange(text);
				focusSelection(text.length);
			}
			return;
		}

		const behavior = composerEnterBehavior(event, isStreaming, supportsSteer);
		if (behavior) {
			event.preventDefault();
			submitText(value, behavior);
		}
	}

	function updateCaret(event: Event): void {
		const target = event.currentTarget;
		if (target instanceof HTMLTextAreaElement) caret = target.selectionStart;
	}

	function handleInput(event: Event): void {
		const target = event.currentTarget;
		if (!(target instanceof HTMLTextAreaElement)) return;
		const next = target.value;
		if (recalledPromptIndex !== null && next !== recentPrompts[recalledPromptIndex]) {
			recalledPromptIndex = null;
		}
		draftSnapshot = next;
		onChange(next);
		caret = target.selectionStart;
	}

	function handlePaste(event: ClipboardEvent): void {
		const files = Array.from(event.clipboardData?.files ?? []);
		const imageFiles = files.filter((file) => file.type.startsWith("image/"));
		if (imageFiles.length === 0) return;
		event.preventDefault();
		if (!attachmentPromptsEnabled) {
			attachErrors = [
				{
					id: randomId(),
					name: "clipboard image",
					reason: "connected agent does not support file attachments",
				},
			];
			return;
		}

		const target = event.currentTarget;
		const eventValue = target instanceof HTMLTextAreaElement ? target.value : draftSnapshot;
		const selectionStart =
			target instanceof HTMLTextAreaElement && eventValue === draftSnapshot
				? target.selectionStart
				: caret;
		const selectionEnd =
			target instanceof HTMLTextAreaElement && eventValue === draftSnapshot
				? target.selectionEnd
				: caret;
		const names = reserveClipboardImageNames(
			imageFiles,
			[
				...images.map((image) => image.name),
				...texts.map((attachment) => attachment.name),
				...reservedImageNames,
			],
			draftSnapshot,
		);
		reservedImageNames = [...reservedImageNames, ...names];
		const insertion = insertImageTags(draftSnapshot, selectionStart, selectionEnd, names);
		replaceDraft(insertion.value, insertion.caret);
		void addFiles(files, names);
	}

	function handleDrop(event: DragEvent): void {
		const files = Array.from(event.dataTransfer?.files ?? []);
		if (files.length === 0) return;
		event.preventDefault();
		if (attachmentPromptsEnabled) {
			void addFiles(files);
			return;
		}
		attachErrors = [
			{
				id: randomId(),
				name: "dropped image",
				reason: "connected agent does not support file attachments",
			},
		];
	}
</script>

<div
	class="relative flex shrink-0 flex-col bg-container-project-bg"
	data-image-prompts={supportsImages === null ? "unknown" : supportsImages}
	data-text-resource-prompts={supportsTextResources === null ? "unknown" : supportsTextResources}
>
	{#if mentionOpen}
		<div
			id={mentionListboxId}
			role="listbox"
			data-testid="mention-menu"
			class="absolute bottom-full left-sm z-10 mb-xs max-h-[40vh] w-[min(28rem,90%)] overflow-y-auto rounded-[var(--radius-md)] border border-border-default bg-container-elevated-bg p-xs shadow-[var(--shadow-md)]"
		>
			{#each mentionCandidates as candidate, index (candidate.kind === "agent" ? candidate.mention : candidate.path)}
				<button
					id={`${mentionListboxId}-option-${index}`}
					role="option"
					aria-selected={index === visibleMentionActiveIndex}
					type="button"
					data-testid="mention-item"
					aria-label={candidate.kind === "agent" ? agentMentionLabel(candidate) : undefined}
					onclick={() => pickMention(candidate)}
					class={`flex w-full items-center gap-sm rounded-[var(--radius-sm)] px-sm py-xs text-left tr-text-ui ${
						index === visibleMentionActiveIndex
							? "bg-control-bg-selected text-text-default"
							: "text-text-muted"
					}`}
				>
					{#if candidate.kind === "agent"}
						<Icon
							name={candidate.sourceType === "skill" || candidate.sourceType === "builtinSkill"
								? "wrench"
								: candidate.sourceType === "recipe" || candidate.sourceType === "subrecipe"
									? "book-open"
									: candidate.sourceType === "project"
										? "puzzle"
										: "bot"}
							size={14}
							class="shrink-0"
						/>
					{:else}
						<Icon name={candidate.kind === "dir" ? "folder" : "file"} size={14} class="shrink-0" />
					{/if}
					{#if candidate.kind === "agent"}
						<span class="min-w-0">
							<span class="block truncate">{candidate.name}</span>
							<span class="block truncate text-text-muted tr-text-metadata">
								{agentMentionSummary(candidate)}
							</span>
						</span>
					{:else}
						<span class="truncate">{candidate.path}</span>
					{/if}
				</button>
			{/each}
		</div>
	{:else if slashOpen}
		<SlashCommandMenu
			commands={slashMatches}
			activeIndex={visibleSlashActiveIndex}
			onSelect={pickSlashCommand}
			class="absolute bottom-full left-sm z-10 mb-xs"
			listboxId={slashListboxId}
		/>
	{/if}

	{#if (imagePromptsEnabled && images.length > 0) || (textResourcesEnabled && texts.length > 0) || pendingAttachments > 0 || attachErrors.length > 0}
		<div class="flex flex-wrap gap-xs px-sm pt-sm" data-testid="composer-attachments">
			{#each attachErrors as error (error.id)}
				<FileChip
					testid="composer-image-error"
					tone="error"
					icon={false}
					title={`Couldn't attach ${error.name} — ${error.reason}`}
					label={`Couldn't attach ${error.name}`}
					meta={`— ${error.reason}`}
					removeLabel="Dismiss"
					onRemove={() => (attachErrors = attachErrors.filter((item) => item.id !== error.id))}
				/>
			{/each}
			{#each images as image (image.id)}
				<FileChip
					testid="composer-image"
					width={image.width}
					height={image.height}
					mime={image.content.mimeType}
					title={image.name}
					label={image.name}
					meta={image.width && image.height ? ` · ${image.width}×${image.height}` : undefined}
					removeLabel="Remove image"
					onRemove={() => removeImage(image)}
				/>
			{/each}
			{#each texts as attachment (attachment.id)}
				<FileChip
					testid="composer-text-attachment"
					title={attachment.name}
					label={attachment.name}
					meta={` · ${utf8ByteLength(attachment.content.text).toLocaleString()} bytes`}
					removeLabel="Remove file"
					onRemove={() =>
					commitTexts(texts.filter((item) => item.id !== attachment.id))}
				/>
			{/each}
			{#if pendingAttachments > 0}
				<FileChip
					testid="composer-attachment-pending"
					label={pendingAttachments === 1 ? "Attaching…" : `Attaching ${pendingAttachments}…`}
				/>
			{/if}
		</div>
	{/if}

	<form
		class="composer composer-shell"
		data-state={isStreaming ? "thinking" : undefined}
		onsubmit={(event) => {
			event.preventDefault();
			submitText(value, isStreaming ? streamingSubmitBehavior(supportsSteer) : "send");
		}}
	>
		<label class="composer-label" for={inputId}>Message</label>
		<textarea
			bind:this={textarea}
			id={inputId}
			data-testid="chat-input"
			role="combobox"
			aria-autocomplete="list"
			aria-expanded={completionOpen}
			aria-controls={completionOpen ? completionListboxId : undefined}
			aria-activedescendant={activeCompletionId}
			{value}
			oninput={handleInput}
			onkeyup={updateCaret}
			onclick={updateCaret}
			onselect={updateCaret}
			onkeydown={handleKeyDown}
			onpaste={handlePaste}
			ondrop={handleDrop}
			rows={4}
			{placeholder}
			class="composer-input min-h-[108px]"
		></textarea>

		<div class="composer-actions">
			<div class="composer-actions-leading"></div>
			<div class="composer-actions-trailing">
				<input
					bind:this={fileInput}
					type="file"
					accept={acceptedAttachments}
					multiple
					tabindex="-1"
					aria-hidden="true"
					class="sr-only"
					onchange={(event) => {
						const files = Array.from(event.currentTarget.files ?? []);
						event.currentTarget.value = "";
						void addFiles(files);
					}}
				/>
				<Button
					variant="outline"
					size="icon-sm"
					data-testid="file-attach"
					aria-label="Attach files or images"
					title="Attach files or images"
					disabled={!attachmentPromptsEnabled}
					onclick={() => fileInput?.click()}
				>
					<Icon name="paperclip" size={14} />
				</Button>
				<Button
					variant="outline"
					size="icon-sm"
					data-testid="history-open"
					aria-label="Search history"
					onclick={openHistory}
				>
					<Icon name="clock-arrow-left" size={14} />
				</Button>
				{#if isStreaming}
					<Button
						variant="outline"
						size="icon-sm"
						data-testid="chat-abort"
						aria-label="Stop"
						onclick={onAbort}
					>
						<Icon name="square" size={14} />
					</Button>
					<span class="contents" {@attach mewa(dropdownBehavior)}>
						<Button
							variant="outline"
							size="icon-sm"
							data-testid="send-menu"
							data-dropdown-menu-trigger={sendMenuId}
							aria-haspopup="menu"
							aria-controls={sendMenuId}
							aria-expanded="false"
							aria-label="Send options"
						>
							<Icon name="chevron-up" size={14} />
						</Button>
						<div
							bind:this={sendMenu}
							id={sendMenuId}
							popover="auto"
							role="menu"
							class="dropdown-menu-content send-menu"
							data-align="end"
						>
							{#each streamingSendModes(supportsSteer) as mode (mode.behavior)}
								<button
									type="button"
									role="menuitem"
									data-testid={mode.testid}
									disabled={!canSubmit(value)}
									onclick={() => {
										sendMenu?.hidePopover();
										submitText(value, mode.behavior);
									}}
									class="dropdown-menu-item flex-col items-stretch gap-2xs"
								>
									<span class="flex w-full items-baseline justify-between gap-sm">
										<span class="text-text-default tr-text-ui">{mode.name}</span>
										<span class="shrink-0 text-text-muted tr-text-metadata">{mode.keys}</span>
									</span>
									<span class="text-text-muted tr-text-metadata">{mode.meaning}</span>
								</button>
							{/each}
						</div>
					</span>
				{/if}
				<Button
					size="icon-sm"
					data-testid="chat-send"
					aria-label={isStreaming ? (supportsSteer ? "Steer" : "Queue follow-up") : "Send"}
					disabled={!canSubmit(value)}
					onclick={() =>
						submitText(value, isStreaming ? streamingSubmitBehavior(supportsSteer) : "send")}
				>
					<Icon name="arrow-up" size={16} />
				</Button>
			</div>
		</div>
	</form>
</div>

<style>
	.composer-shell {
		border-inline: 0;
		border-block-end: 0;
	}

	.send-menu {
		left: auto;
		right: anchor(right);
		bottom: anchor(top);
		top: auto;
		width: min(20rem, calc(100vw - 2rem));
		margin-bottom: var(--space-100);
	}
</style>

// gooseberry/webui/src/chat/composer.tsx
import { REQUEST_IMAGE_BASE64_BUDGET, type SlashCommandInfo } from "@gooseberry/contracts";
import {
	ArrowUp,
	BookOpen,
	Bot,
	ChevronUp,
	FileIcon,
	FolderIcon,
	History,
	Puzzle,
	Square,
	Wrench,
	X,
} from "lucide-react";
import {
	type ClipboardEvent,
	type DragEvent,
	forwardRef,
	type KeyboardEvent,
	useCallback,
	useEffect,
	useId,
	useImperativeHandle,
	useLayoutEffect,
	useRef,
	useState,
} from "react";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { FileChip } from "./file-chip";
import { type AttachedImage, fileToAttachedImage } from "./image-attachment";
import {
	SlashCommandMenu,
	selectedSlashCommandValue,
	useSlashCommandCompletion,
} from "./slash-command-completion";
import type { ChatAttachment } from "./types";

export type SubmitBehavior = "send" | "steer" | "queue" | "interrupt";

export function streamingSubmitBehavior(supportsSteer: boolean): "steer" | "queue" {
	return supportsSteer ? "steer" : "queue";
}

const STREAMING_SEND_MODES = [
	{
		behavior: "queue" as const,
		name: "Queue follow-up",
		meaning: "runs after the agent finishes",
		keys: "Cmd/Ctrl+Enter",
		testid: "send-mode-queue",
	},
	{
		behavior: "steer" as const,
		name: "Steer",
		meaning: "delivers at the agent's next step",
		keys: "Enter",
		testid: "send-mode-steer",
	},
	{
		behavior: "interrupt" as const,
		name: "Interrupt",
		meaning: "stops the current response and sends now",
		keys: "Cmd/Ctrl+Shift+Enter",
		testid: "send-mode-interrupt",
	},
];

export function streamingSendModes(supportsSteer: boolean) {
	return supportsSteer
		? STREAMING_SEND_MODES
		: STREAMING_SEND_MODES.filter((mode) => mode.behavior !== "steer");
}

export type MentionCandidate =
	| { path: string; name: string; kind: "file" | "dir" }
	| {
			name: string;
			description: string;
			sourceType: "skill" | "builtinSkill" | "recipe" | "subrecipe" | "agent" | "project";
			mention: string;
			kind: "agent";
	  };

export function insertedMention(candidate: MentionCandidate): string {
	return candidate.kind === "agent"
		? candidate.mention
		: candidate.kind === "dir"
			? `@${candidate.path}/`
			: `@${candidate.path}`;
}

export function agentMentionLabel(candidate: Extract<MentionCandidate, { kind: "agent" }>): string {
	return `${agentMentionTypeLabel(candidate.sourceType)} mention: ${candidate.name}. ${candidate.description}`;
}

export function agentMentionSummary(
	candidate: Extract<MentionCandidate, { kind: "agent" }>,
): string {
	return `${agentMentionTypeLabel(candidate.sourceType)} · ${candidate.description}`;
}

export function agentMentionTypeLabel(
	sourceType: Extract<MentionCandidate, { kind: "agent" }>["sourceType"],
): string {
	return {
		skill: "skill",
		builtinSkill: "built-in skill",
		recipe: "recipe",
		subrecipe: "subrecipe",
		agent: "agent",
		project: "project",
	}[sourceType];
}

function AgentMentionIcon({
	sourceType,
}: {
	sourceType: Extract<MentionCandidate, { kind: "agent" }>["sourceType"];
}) {
	const props = { className: "size-3.5 shrink-0", "aria-hidden": true };
	if (sourceType === "skill" || sourceType === "builtinSkill") return <Wrench {...props} />;
	if (sourceType === "recipe" || sourceType === "subrecipe") return <BookOpen {...props} />;
	if (sourceType === "project") return <Puzzle {...props} />;
	return <Bot {...props} />;
}

export function clampedMentionActiveIndex(activeIndex: number, candidateCount: number): number {
	return candidateCount > 0 ? Math.min(Math.max(activeIndex, 0), candidateCount - 1) : 0;
}

export type MentionCompletionKeyAction =
	| { type: "none" }
	| { type: "move"; index: number }
	| { type: "select"; index: number }
	| { type: "dismiss" };

export function mentionCompletionKeyAction(
	key: string,
	open: boolean,
	activeIndex: number,
	candidateCount: number,
): MentionCompletionKeyAction {
	if (!open || candidateCount === 0) return { type: "none" };
	const visibleIndex = clampedMentionActiveIndex(activeIndex, candidateCount);
	if (key === "ArrowDown") return { type: "move", index: (visibleIndex + 1) % candidateCount };
	if (key === "ArrowUp") {
		return { type: "move", index: (visibleIndex - 1 + candidateCount) % candidateCount };
	}
	if (key === "Enter" || key === "Tab") return { type: "select", index: visibleIndex };
	if (key === "Escape") return { type: "dismiss" };
	return { type: "none" };
}

interface PendingImage extends AttachedImage {
	id: string;
	name: string;
}

interface AttachError {
	id: string;
	name: string;
	reason: string;
}

function activeToken(value: string, caret: number): { token: string; start: number } {
	const match = /(\S+)$/.exec(value.slice(0, caret));
	if (!match) return { token: "", start: caret };
	return { token: match[0], start: caret - match[0].length };
}

interface ComposerProps {
	value: string;
	onChange: (value: string) => void;
	isStreaming: boolean;
	commands: SlashCommandInfo[];
	mentionCandidates: MentionCandidate[];
	recentPrompts: string[];
	onMentionQuery: (query: string | null) => void;
	onSubmit: (
		text: string,
		attachments: ChatAttachment[],
		behavior: SubmitBehavior,
	) => boolean | undefined;
	onAbort: () => void;
	onHistoryOpen?: () => void;
	supportsImages?: boolean | null;
	supportsSteer?: boolean;
}

export interface ComposerHandle {
	insertText: (text: string) => void;
	insertAndSubmit: (text: string, behavior: SubmitBehavior) => void;
	openHistory: () => void;
	refocus: () => void;
}

export const Composer = forwardRef<ComposerHandle, ComposerProps>(function Composer(
	{
		value,
		onChange,
		isStreaming,
		commands,
		mentionCandidates,
		recentPrompts,
		onMentionQuery,
		onSubmit,
		onAbort,
		onHistoryOpen,
		supportsImages = true,
		supportsSteer = true,
	},
	handleRef,
) {
	const ref = useRef<HTMLTextAreaElement>(null);
	const [caret, setCaret] = useState(value.length);
	const [images, setImages] = useState<PendingImage[]>([]);
	const imagesRef = useRef<PendingImage[]>([]);
	const supportsImagesRef = useRef(supportsImages);
	supportsImagesRef.current = supportsImages;
	const imagePromptsEnabled = supportsImages !== false;
	const commitImages = (next: PendingImage[]) => {
		imagesRef.current = next;
		setImages(next);
	};
	const [pendingImages, setPendingImages] = useState(0);
	const [attachErrors, setAttachErrors] = useState<AttachError[]>([]);
	const [mentionActiveIndex, setMentionActiveIndex] = useState(0);
	const [mentionDismissed, setMentionDismissed] = useState(false);
	const [sendMenuOpen, setSendMenuOpen] = useState(false);
	const recallIdxRef = useRef<number | null>(null);

	const { token, start } = activeToken(value, caret);
	const mentionQuery = token.startsWith("@") ? token.slice(1) : null;

	useEffect(() => onMentionQuery(mentionQuery), [mentionQuery, onMentionQuery]);
	// biome-ignore lint/correctness/useExhaustiveDependencies: reset selection when the query changes
	useEffect(() => {
		setMentionActiveIndex(0);
		setMentionDismissed(false);
	}, [mentionQuery]);
	useEffect(() => {
		setMentionActiveIndex((index) => clampedMentionActiveIndex(index, mentionCandidates.length));
	}, [mentionCandidates.length]);
	useEffect(() => {
		if (supportsImages !== false) return;
		const removedImages = imagesRef.current.length > 0 || pendingImages > 0;
		imagesRef.current = [];
		setImages([]);
		if (removedImages) {
			setAttachErrors([
				{
					id: crypto.randomUUID(),
					name: "images",
					reason: "connected agent does not support image prompts",
				},
			]);
		}
	}, [supportsImages, pendingImages]);

	const mentionOpen = !mentionDismissed && mentionQuery !== null && mentionCandidates.length > 0;
	const visibleMentionActiveIndex = clampedMentionActiveIndex(
		mentionActiveIndex,
		mentionCandidates.length,
	);
	const mentionListboxId = useId();
	const slashListboxId = useId();

	const [pendingSelection, setPendingSelection] = useState<{ start: number; end: number } | null>(
		null,
	);

	useLayoutEffect(() => {
		if (pendingSelection === null) return;
		const el = ref.current;
		if (el) {
			el.focus();
			el.setSelectionRange(pendingSelection.start, pendingSelection.end);
		}
		setCaret(pendingSelection.start);
		setPendingSelection(null);
	}, [pendingSelection]);

	const focusSelection = useCallback((start: number, end: number = start) => {
		setPendingSelection({ start, end });
	}, []);

	const replaceDraft = useCallback(
		(text: string, caret: number = text.length) => {
			recallIdxRef.current = null;
			onChange(text);
			focusSelection(caret);
		},
		[onChange, focusSelection],
	);

	const canSubmit = (raw: string) =>
		pendingImages === 0 && (!!raw.trim() || (imagePromptsEnabled && images.length > 0));

	const submitText = (raw: string, behavior: SubmitBehavior) => {
		if (!canSubmit(raw)) return;
		const text = raw.trim();
		const accepted = onSubmit(
			text,
			imagePromptsEnabled ? images.map(({ name, content }) => ({ name, content })) : [],
			behavior,
		);
		if (accepted === false) return;
		onChange("");
		commitImages([]);
		setAttachErrors([]);
		recallIdxRef.current = null;
	};

	const pickMention = (c: MentionCandidate) => {
		const before = value.slice(0, start);
		const after = value.slice(caret);
		const insert = insertedMention(c);
		const suffix = c.kind === "dir" ? "" : " ";
		replaceDraft(
			`${before}${insert}${suffix}${after}`,
			before.length + insert.length + suffix.length,
		);
	};

	const slashCompletion = useSlashCommandCompletion({
		value,
		commands,
		onSelect: (command) => replaceDraft(selectedSlashCommandValue(command)),
	});
	const completionOpen = mentionOpen || slashCompletion.open;
	const activeCompletionId = mentionOpen
		? `${mentionListboxId}-option-${visibleMentionActiveIndex}`
		: slashCompletion.open
			? `${slashListboxId}-option-${slashCompletion.activeIndex}`
			: undefined;
	const completionListboxId = mentionOpen ? mentionListboxId : slashListboxId;

	const openHistory = () => {
		setMentionDismissed(true);
		slashCompletion.dismiss();
		onHistoryOpen?.();
	};

	useImperativeHandle(handleRef, () => ({
		insertText: (text: string) => replaceDraft(text),
		insertAndSubmit: (text: string, behavior: SubmitBehavior) =>
			canSubmit(text) ? submitText(text, behavior) : replaceDraft(text),
		openHistory,
		refocus: () => {
			focusSelection(caret);
		},
	}));

	const addFiles = async (files: File[]) => {
		if (!imagePromptsEnabled) return;
		const picked = files.filter((f) => f.type.startsWith("image/"));
		if (picked.length === 0) return;
		setPendingImages((n) => n + picked.length);
		try {
			const settled = await Promise.allSettled(picked.map(fileToAttachedImage));
			let used = imagesRef.current.reduce((sum, p) => sum + p.content.data.length, 0);
			const additions: PendingImage[] = [];
			const errors: AttachError[] = [];
			settled.forEach((result, i) => {
				const name = picked[i]?.name || "image";
				if (result.status !== "fulfilled" || result.value === null) {
					errors.push({ id: crypto.randomUUID(), name, reason: "unsupported image format" });
					return;
				}
				const size = result.value.content.data.length;
				if (used + size > REQUEST_IMAGE_BASE64_BUDGET) {
					errors.push({ id: crypto.randomUUID(), name, reason: "message image limit reached" });
					return;
				}
				used += size;
				additions.push({
					id: crypto.randomUUID(),
					name,
					...result.value,
				});
			});
			if (supportsImagesRef.current !== false && additions.length > 0) {
				commitImages([...imagesRef.current, ...additions]);
			}
			if (supportsImagesRef.current !== false && errors.length > 0) {
				setAttachErrors((prev) => [...prev, ...errors]);
			}
		} finally {
			setPendingImages((n) => n - picked.length);
		}
	};

	const submit = (behavior: SubmitBehavior) => {
		submitText(value, behavior);
	};

	const onKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
		if (mentionOpen) {
			const action = mentionCompletionKeyAction(
				e.key,
				mentionOpen,
				visibleMentionActiveIndex,
				mentionCandidates.length,
			);
			if (action.type !== "none") {
				e.preventDefault();
				if (action.type === "move") setMentionActiveIndex(action.index);
				if (action.type === "dismiss") setMentionDismissed(true);
				if (action.type === "select") {
					const candidate = mentionCandidates[action.index];
					if (candidate) pickMention(candidate);
				}
				return;
			}
		}
		if (slashCompletion.handleKeyDown(e)) return;
		const recallAt = recallIdxRef.current;
		if (e.key === "ArrowUp" && (value === "" || recallAt !== null) && recentPrompts.length > 0) {
			e.preventDefault();
			const next = recallAt === null ? 0 : Math.min(recallAt + 1, recentPrompts.length - 1);
			const text = recentPrompts[next] ?? "";
			recallIdxRef.current = next;
			onChange(text);
			focusSelection(text.length);
			return;
		}
		if (e.key === "ArrowDown" && recallAt !== null) {
			e.preventDefault();
			if (recallAt === 0) {
				recallIdxRef.current = null;
				onChange("");
				focusSelection(0);
			} else {
				const next = recallAt - 1;
				const text = recentPrompts[next] ?? "";
				recallIdxRef.current = next;
				onChange(text);
				focusSelection(text.length);
			}
			return;
		}
		if (e.key === "Enter" && e.shiftKey && (e.metaKey || e.ctrlKey)) {
			e.preventDefault();
			submit(isStreaming ? "interrupt" : "send");
			return;
		}
		if (e.key === "Enter" && !e.shiftKey && (e.metaKey || e.ctrlKey)) {
			e.preventDefault();
			submit(isStreaming ? "queue" : "send");
			return;
		}
		if (e.key === "Enter" && !e.shiftKey) {
			e.preventDefault();
			const behavior: SubmitBehavior = isStreaming
				? streamingSubmitBehavior(supportsSteer)
				: "send";
			submit(behavior);
		}
	};

	const onPaste = (e: ClipboardEvent<HTMLTextAreaElement>) => {
		const files = [...e.clipboardData.files];
		if (files.length > 0 && imagePromptsEnabled) {
			e.preventDefault();
			void addFiles(files);
		} else if (files.length > 0) {
			setAttachErrors([
				{
					id: crypto.randomUUID(),
					name: "clipboard image",
					reason: "connected agent does not support image prompts",
				},
			]);
		}
	};

	const onDrop = (e: DragEvent<HTMLTextAreaElement>) => {
		if (e.dataTransfer.files.length > 0) {
			e.preventDefault();
			if (imagePromptsEnabled) {
				void addFiles([...e.dataTransfer.files]);
			} else {
				setAttachErrors([
					{
						id: crypto.randomUUID(),
						name: "dropped image",
						reason: "connected agent does not support image prompts",
					},
				]);
			}
		}
	};

	return (
		<div
			className="relative flex shrink-0 flex-col border-border-muted border-t bg-container-project-bg"
			data-image-prompts={supportsImages === null ? "unknown" : supportsImages}
		>
			{mentionOpen ? (
				<div
					id={mentionListboxId}
					role="listbox"
					data-testid="mention-menu"
					className="absolute bottom-full left-sm mb-xs max-h-[40vh] w-[min(28rem,90%)] overflow-y-auto rounded-[var(--radius-md)] border border-border-default bg-container-elevated-bg p-xs shadow-[var(--shadow-md)]"
				>
					{mentionCandidates.map((candidate, index) => (
						<button
							key={candidate.kind === "agent" ? candidate.mention : candidate.path}
							id={`${mentionListboxId}-option-${index}`}
							role="option"
							aria-selected={index === visibleMentionActiveIndex}
							type="button"
							data-testid="mention-item"
							aria-label={candidate.kind === "agent" ? agentMentionLabel(candidate) : undefined}
							onClick={() => pickMention(candidate)}
							className={`flex w-full items-center gap-sm rounded-[var(--radius-sm)] px-sm py-xs text-left tr-text-ui ${index === visibleMentionActiveIndex ? "bg-control-bg-selected text-text-default" : "text-text-muted"}`}
						>
							{candidate.kind === "agent" ? (
								<AgentMentionIcon sourceType={candidate.sourceType} />
							) : candidate.kind === "dir" ? (
								<FolderIcon className="size-3.5 shrink-0" />
							) : (
								<FileIcon className="size-3.5 shrink-0" />
							)}
							{candidate.kind === "agent" ? (
								<span className="min-w-0">
									<span className="block truncate">{candidate.name}</span>
									<span className="block truncate text-text-muted tr-text-metadata">
										{agentMentionSummary(candidate)}
									</span>
								</span>
							) : (
								<span className="truncate">{candidate.path}</span>
							)}
						</button>
					))}
				</div>
			) : slashCompletion.open ? (
				<SlashCommandMenu
					commands={slashCompletion.matches}
					activeIndex={slashCompletion.activeIndex}
					onSelect={slashCompletion.pick}
					className="absolute bottom-full left-sm mb-xs"
					listboxId={slashListboxId}
				/>
			) : null}

			{(imagePromptsEnabled && (images.length > 0 || pendingImages > 0)) ||
			attachErrors.length > 0 ? (
				<div className="flex flex-wrap gap-xs px-sm pt-sm" data-testid="composer-images">
					{attachErrors.map((err) => (
						<FileChip
							key={err.id}
							data-testid="composer-image-error"
							tone="error"
							icon={false}
							title={`Couldn't attach ${err.name} — ${err.reason}`}
							label={`Couldn't attach ${err.name}`}
							meta={`— ${err.reason}`}
							trailing={
								<button
									type="button"
									aria-label="Dismiss"
									onClick={() => setAttachErrors((prev) => prev.filter((p) => p.id !== err.id))}
									className="hover:opacity-80"
								>
									<X className="size-3" />
								</button>
							}
						/>
					))}
					{images.map((img) => (
						<FileChip
							key={img.id}
							data-testid="composer-image"
							data-width={img.width}
							data-height={img.height}
							data-mime={img.content.mimeType}
							title={img.name}
							label={img.name}
							meta={img.width && img.height ? ` · ${img.width}×${img.height}` : undefined}
							trailing={
								<button
									type="button"
									aria-label="Remove image"
									onClick={() => commitImages(imagesRef.current.filter((p) => p.id !== img.id))}
									className="text-text-muted hover:text-text-default"
								>
									<X className="size-3" />
								</button>
							}
						/>
					))}
					{pendingImages > 0 ? (
						<FileChip
							data-testid="composer-image-pending"
							label={
								<span className="text-text-muted">
									{pendingImages === 1 ? "Attaching…" : `Attaching ${pendingImages}…`}
								</span>
							}
						/>
					) : null}
				</div>
			) : null}

			<div className="flex flex-col gap-sm p-sm">
				<div className="relative rounded-[var(--radius-md)] border border-control-border-default bg-control-bg bg-clip-padding transition-colors focus-within:border-control-border-active">
					<textarea
						ref={ref}
						data-testid="chat-input"
						role="combobox"
						aria-autocomplete="list"
						aria-expanded={completionOpen}
						aria-controls={completionOpen ? completionListboxId : undefined}
						aria-activedescendant={activeCompletionId}
						value={value}
						onChange={(e) => {
							const next = e.target.value;
							const nextCaret = e.target.selectionStart;
							const recalled = recallIdxRef.current;
							if (recalled !== null && next !== recentPrompts[recalled]) {
								recallIdxRef.current = null;
							}
							onChange(next);
							setCaret(nextCaret);
						}}
						onKeyUp={(e) => setCaret(e.currentTarget.selectionStart)}
						onClick={(e) => setCaret(e.currentTarget.selectionStart)}
						onKeyDown={onKeyDown}
						onPaste={onPaste}
						onDrop={onDrop}
						rows={4}
						placeholder={
							isStreaming
								? supportsSteer
									? "Enter steers at the next step · Cmd/Ctrl+Enter queues for when it finishes"
									: "Enter queues a follow-up for when the agent finishes"
								: "Message the agent…  (@ files · / commands · Enter to send)"
						}
						className="relative min-h-[108px] w-full resize-none rounded-[var(--radius-sm)] bg-transparent px-md py-sm tr-text-ui text-text-default outline-none placeholder:text-text-muted"
					/>
				</div>
				<div className="flex flex-wrap items-center gap-sm">
					<div className="min-w-0 flex-1" />
					<div className="flex shrink-0 items-center gap-sm">
						<button
							type="button"
							data-testid="history-open"
							aria-label="Search history"
							onClick={openHistory}
							className="flex size-8 shrink-0 items-center justify-center rounded-[var(--radius-sm)] border border-border-default bg-container-elevated-bg text-text-default hover:bg-control-bg-hovered"
						>
							<History className="size-3.5" />
						</button>
						{isStreaming ? (
							<button
								type="button"
								data-testid="chat-abort"
								aria-label="Stop"
								onClick={onAbort}
								className="flex size-8 shrink-0 items-center justify-center rounded-[var(--radius-sm)] border border-border-default bg-container-elevated-bg text-text-default hover:bg-control-bg-hovered"
							>
								<Square className="size-3.5" />
							</button>
						) : null}
						{isStreaming ? (
							<Popover open={sendMenuOpen} onOpenChange={setSendMenuOpen}>
								<PopoverTrigger asChild>
									<button
										type="button"
										data-testid="send-menu"
										aria-label="Send options"
										className="flex size-8 shrink-0 items-center justify-center rounded-[var(--radius-sm)] border border-border-default bg-container-elevated-bg text-text-default hover:bg-control-bg-hovered"
									>
										<ChevronUp className="size-3.5" />
									</button>
								</PopoverTrigger>
								<PopoverContent side="top" align="end" className="w-[320px] p-xs">
									<div className="flex flex-col gap-2xs">
										{streamingSendModes(supportsSteer).map((mode) => (
											<button
												key={mode.behavior}
												type="button"
												data-testid={mode.testid}
												disabled={!canSubmit(value)}
												onClick={() => {
													setSendMenuOpen(false);
													submit(mode.behavior);
												}}
												className="flex w-full flex-col gap-2xs rounded-[var(--radius-sm)] px-sm py-xs text-left hover:bg-control-bg-hovered disabled:pointer-events-none disabled:opacity-50"
											>
												<span className="flex w-full items-baseline justify-between gap-sm">
													<span className="text-text-default tr-text-ui">{mode.name}</span>
													<span className="shrink-0 text-text-muted tr-text-metadata">
														{mode.keys}
													</span>
												</span>
												<span className="text-text-muted tr-text-metadata">{mode.meaning}</span>
											</button>
										))}
									</div>
								</PopoverContent>
							</Popover>
						) : null}
						<button
							type="button"
							data-testid="chat-send"
							aria-label={isStreaming ? (supportsSteer ? "Steer" : "Queue follow-up") : "Send"}
							onClick={() => submit(isStreaming ? streamingSubmitBehavior(supportsSteer) : "send")}
							disabled={!canSubmit(value)}
							className="flex size-8 shrink-0 items-center justify-center rounded-[var(--radius-sm)] bg-control-primary-bg text-control-primary-text hover:bg-control-primary-bg-hovered disabled:pointer-events-none disabled:bg-control-primary-disabled-bg disabled:text-control-primary-disabled-text"
						>
							<ArrowUp className="size-4" />
						</button>
					</div>
				</div>
			</div>
		</div>
	);
});
