// gooseberry/webui/src/components/confirm-dialog.svelte
<script lang="ts">
import type { Snippet } from "svelte";
import Button from "./button.svelte";
import Dialog from "./dialog.svelte";
import Icon from "./icon.svelte";

interface Props {
	open?: boolean;
	title: string;
	description?: string | undefined;
	descriptionContent?: Snippet;
	confirmLabel?: string;
	cancelLabel?: string;
	destructive?: boolean;
	confirmTestId?: string;
	onConfirm: () => void | Promise<void>;
	onOpenChange?: ((open: boolean) => void) | undefined;
	onClosedAutoFocus?: (() => void) | undefined;
}

let {
	open = $bindable(false),
	title,
	description,
	descriptionContent,
	confirmLabel = "Confirm",
	cancelLabel = "Cancel",
	destructive = false,
	confirmTestId,
	onConfirm,
	onOpenChange,
	onClosedAutoFocus,
}: Props = $props();

function setOpen(next: boolean): void {
	open = next;
	onOpenChange?.(next);
}

async function confirm(): Promise<void> {
	await onConfirm();
	setOpen(false);
}
</script>

<Dialog
	bind:open
	role="alertdialog"
	{title}
	{description}
	hideClose
	testid="confirm-dialog"
	class="max-w-[24rem]"
	{onClosedAutoFocus}
	onOpenChange={setOpen}
>
	{#if descriptionContent}
		<div class="dialog-description">{@render descriptionContent()}</div>
	{/if}
	{#snippet actions()}
		<Button variant="outline" onclick={() => setOpen(false)}>{cancelLabel}</Button>
		<Button
			variant={destructive ? "destructive" : "default"}
			data-testid={confirmTestId}
			onclick={confirm}
		>
			{#if destructive}<Icon name="triangle-alert" size={16} />{/if}
			{confirmLabel}
		</Button>
	{/snippet}
</Dialog>

// gooseberry/webui/src/components/confirm-dialog.tsx
import { TriangleAlert } from "lucide-react";
import type { ReactNode } from "react";
import { Button } from "./ui/button";
import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogFooter,
	DialogHeader,
	DialogTitle,
} from "./ui/dialog";

export function ConfirmDialog({
	open,
	onOpenChange,
	title,
	description,
	confirmLabel = "Confirm",
	cancelLabel = "Cancel",
	destructive = false,
	confirmTestId,
	onConfirm,
	onClosedAutoFocus,
}: {
	open: boolean;
	onOpenChange: (open: boolean) => void;
	title: string;
	description?: ReactNode;
	confirmLabel?: string;
	cancelLabel?: string;
	destructive?: boolean;
	confirmTestId?: string;
	onConfirm: () => void;
	onClosedAutoFocus?: () => void;
}) {
	return (
		<Dialog open={open} onOpenChange={onOpenChange}>
			<DialogContent
				role="alertdialog"
				className="max-w-[24rem]"
				hideClose
				data-testid="confirm-dialog"
				onCloseAutoFocus={
					onClosedAutoFocus
						? (event) => {
								event.preventDefault();
								onClosedAutoFocus();
							}
						: undefined
				}
			>
				<DialogHeader>
					<div className="flex items-center gap-sm">
						{destructive ? <TriangleAlert className="size-4 shrink-0 text-feedback-error" /> : null}
						<DialogTitle>{title}</DialogTitle>
					</div>
					{description ? <DialogDescription>{description}</DialogDescription> : null}
				</DialogHeader>
				<DialogFooter>
					<Button variant="outline" onClick={() => onOpenChange(false)}>
						{cancelLabel}
					</Button>
					<Button
						variant={destructive ? "destructive" : "default"}
						data-testid={confirmTestId}
						onClick={() => {
							onConfirm();
							onOpenChange(false);
						}}
					>
						{confirmLabel}
					</Button>
				</DialogFooter>
			</DialogContent>
		</Dialog>
	);
}
