// gooseberry/webui/src/chat/history-overlay.tsx
import type { HistoryScope, MessageHit, PromptHit } from "@gooseberry/contracts";
import { Check, CornerUpRight, Trash2 } from "lucide-react";
import { type KeyboardEvent, useEffect, useMemo, useRef, useState } from "react";
import {
	DropdownMenu,
	DropdownMenuContent,
	DropdownMenuItem,
	DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { relativeTime } from "@/lib";
import {
	type ChatLocationRequest,
	type HistorySearchState,
	type HistorySelection,
	jumpTarget,
	resolveHistorySelection,
	SCOPE_ORDER,
} from "./use-history-search";

const SCOPE_LABELS: Record<HistoryScope["kind"], string> = {
	chat: "Chat",
	project: "Project",
	all: "All",
};

const SCOPE_MENU_LABELS: Record<HistoryScope["kind"], string> = {
	chat: "This chat",
	project: "Project",
	all: "Everywhere",
};

function escapeRegExp(term: string): string {
	return term.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function Highlight({ text, query }: { text: string; query: string }) {
	const terms = [...new Set(query.toLowerCase().split(/\s+/).filter(Boolean))].sort(
		(a, b) => b.length - a.length,
	);
	if (terms.length === 0) return <>{text}</>;
	const pattern = new RegExp(`(${terms.map(escapeRegExp).join("|")})`, "gi");
	let offset = 0;
	const parts = text.split(pattern).map((part) => {
		const start = offset;
		offset += part.length;
		return { text: part, key: `${start}:${part}` };
	});
	return (
		<>
			{parts.map(({ text: part, key }) =>
				terms.includes(part.toLowerCase()) ? (
					<mark key={key} className="rounded-[var(--radius-xs)] bg-primary-soft text-text-default">
						{part}
					</mark>
				) : (
					<span key={key}>{part}</span>
				),
			)}
		</>
	);
}

function DeleteChatButton({
	projectAreaId,
	sessionId,
	isSelected,
	onDeleteChat,
}: {
	projectAreaId: string | undefined;
	sessionId: string;
	isSelected: boolean;
	onDeleteChat: (projectAreaId: string, sessionId: string) => void;
}) {
	if (!projectAreaId) return null;
	return (
		<button
			type="button"
			data-testid="history-delete-chat"
			aria-label="Move chat to trash"
			title="Move chat to trash"
			onClick={(event) => {
				event.stopPropagation();
				onDeleteChat(projectAreaId, sessionId);
			}}
			className={`flex shrink-0 items-center justify-center rounded-[var(--radius-sm)] p-xs text-text-muted opacity-0 transition hover:bg-container-elevated-bg hover:text-feedback-error group-hover:opacity-100 ${
				isSelected ? "opacity-100" : ""
			}`}
		>
			<Trash2 className="size-3.5" />
		</button>
	);
}

function PromptRow({
	hit,
	query,
	scope,
	projectAreaName,
	isSelected,
	onPick,
	onOpenMessage,
	onDeleteChat,
}: {
	hit: PromptHit;
	query: string;
	scope: HistoryScope;
	projectAreaName: string | undefined;
	isSelected: boolean;
	onPick: () => void;
	onOpenMessage: (target: ChatLocationRequest) => void;
	onDeleteChat: (projectAreaId: string, sessionId: string) => void;
}) {
	const firstLine = hit.text.split("\n")[0] ?? hit.text;
	const showChip = (scope.kind === "project" || scope.kind === "all") && !!hit.projectId;
	const target = jumpTarget(hit);
	return (
		<div
			data-testid="history-item"
			data-kind="prompt"
			data-selected={isSelected}
			className={`group flex w-full items-center gap-xs rounded-[var(--radius-sm)] border-l-2 py-xs pl-sm pr-xs text-left tr-text-ui ${
				isSelected
					? "border-l-primary bg-control-bg-selected text-text-default"
					: "border-l-transparent text-text-muted"
			}`}
		>
			<button
				type="button"
				onClick={onPick}
				className="flex min-w-0 flex-1 items-center gap-sm overflow-hidden text-left"
			>
				<span className="min-w-0 flex-1 overflow-hidden whitespace-nowrap text-ellipsis">
					<Highlight text={firstLine} query={query} />
				</span>
				{showChip ? (
					<span className="shrink-0 rounded-full border border-border-default bg-container-project-bg px-xs text-text-muted tr-text-metadata">
						{projectAreaName ?? "projectArea"}
					</span>
				) : null}
				<span className="shrink-0 text-text-muted tr-text-metadata">
					{relativeTime(hit.timestamp)}
				</span>
			</button>
			{target ? (
				<>
					{isSelected ? (
						<span
							data-testid="history-jump-shortcut"
							className="shrink-0 text-text-muted tr-text-metadata"
						>
							⇧⏎
						</span>
					) : null}
					<button
						type="button"
						data-testid="history-jump"
						aria-label="Go to chat"
						title="⇧⏎ go to chat"
						onClick={(e) => {
							e.stopPropagation();
							onOpenMessage(target);
						}}
						className={`flex shrink-0 items-center justify-center rounded-[var(--radius-sm)] p-xs text-text-muted opacity-0 transition hover:bg-container-elevated-bg hover:text-text-default group-hover:opacity-100 ${
							isSelected ? "opacity-100" : ""
						}`}
					>
						<CornerUpRight className="size-3.5" />
					</button>
				</>
			) : null}
			<DeleteChatButton
				projectAreaId={hit.projectId}
				sessionId={hit.sessionId}
				isSelected={isSelected}
				onDeleteChat={onDeleteChat}
			/>
		</div>
	);
}

function MessageRow({
	hit,
	query,
	isSelected,
	onPick,
	onDeleteChat,
}: {
	hit: MessageHit;
	query: string;
	isSelected: boolean;
	onPick: () => void;
	onDeleteChat: (projectAreaId: string, sessionId: string) => void;
}) {
	const unmapped = !hit.projectId;
	return (
		<div
			data-testid="history-item"
			data-kind="message"
			data-selected={isSelected}
			className={`group flex w-full items-center gap-xs rounded-[var(--radius-sm)] border-l-2 pr-xs tr-text-ui ${
				isSelected
					? "border-l-primary bg-control-bg-selected text-text-default"
					: "border-l-transparent text-text-muted"
			}`}
		>
			<button
				type="button"
				onClick={onPick}
				disabled={unmapped}
				className="flex min-w-0 flex-1 flex-col gap-0.5 px-sm py-xs text-left disabled:cursor-default"
			>
				<span className="flex items-center gap-xs text-text-muted tr-text-metadata">
					<span className="truncate">
						{hit.sessionTitle || hit.cwd.split("/").pop() || "session"}
					</span>
					<span>·</span>
					<span>{hit.role}</span>
					<span>·</span>
					<span>{relativeTime(hit.timestamp)}</span>
					{unmapped ? <span>· not a gooseberry projectArea</span> : null}
				</span>
				<span className="overflow-hidden whitespace-nowrap text-ellipsis">
					<Highlight text={hit.snippet} query={query} />
				</span>
			</button>
			<DeleteChatButton
				projectAreaId={hit.projectId}
				sessionId={hit.sessionId}
				isSelected={isSelected}
				onDeleteChat={onDeleteChat}
			/>
		</div>
	);
}

function PromptPreviewFooter({
	hit,
	projectAreaName,
}: {
	hit: PromptHit;
	projectAreaName: string | undefined;
}) {
	const parts = [
		hit.sessionTitle,
		hit.projectId ? (projectAreaName ?? "projectArea") : undefined,
		relativeTime(hit.timestamp),
	].filter((part): part is string => !!part);
	return <>{parts.join(" · ")}</>;
}

function HistoryPreview({
	item,
	query,
	projectAreaName,
	className,
}: {
	item: HistorySelection | null;
	query: string;
	projectAreaName: string | undefined;
	className: string;
}) {
	return (
		<div data-testid="history-preview" className={`flex flex-col overflow-hidden ${className}`}>
			{item ? (
				<>
					<div className="min-h-0 flex-1 overflow-y-auto whitespace-pre-wrap break-words p-sm tr-text-ui text-text-default">
						<Highlight text={item.hit.text} query={query} />
					</div>
					<div className="shrink-0 border-t border-border-default px-sm py-xs text-text-muted tr-text-metadata">
						{item.kind === "prompt" ? (
							<PromptPreviewFooter hit={item.hit} projectAreaName={projectAreaName} />
						) : (
							messageCrumb(item.hit)
						)}
					</div>
				</>
			) : null}
		</div>
	);
}

function messageCrumb(hit: MessageHit): string {
	return `${hit.sessionTitle || hit.cwd.split("/").pop() || "session"} · ${hit.role} · ${relativeTime(hit.timestamp)}`;
}

export interface HistoryOverlayProps {
	state: HistorySearchState;
	projectAreaNames: Record<string, string>;
	onQueryChange: (query: string) => void;
	onToggleStage: () => void;
	onMoveSelection: (delta: number) => void;
	onClose: () => void;
	onInsert: (hit: PromptHit) => void;
	onInsertAndSend: (hit: PromptHit) => void;
	onOpenMessage: (target: ChatLocationRequest) => void;
	onDeleteChat: (projectAreaId: string, sessionId: string) => void;
	onSetScope: (kind: HistoryScope["kind"]) => void;
}

export function HistoryOverlay({
	state,
	projectAreaNames,
	onQueryChange,
	onToggleStage,
	onMoveSelection,
	onClose,
	onInsert,
	onInsertAndSend,
	onOpenMessage,
	onDeleteChat,
	onSetScope,
}: HistoryOverlayProps) {
	const { open, stage, query, scope, result, selected, error } = state;
	const inputRef = useRef<HTMLInputElement>(null);
	const resultsRef = useRef<HTMLDivElement>(null);
	const [scopeMenuOpen, setScopeMenuOpen] = useState(false);

	useEffect(() => {
		if (!open) return;
		const el = inputRef.current;
		if (!el) return;
		el.focus();
		el.select();
	}, [open]);

	useEffect(() => {
		if (!open || scopeMenuOpen) return;
		const onWindowKeyDown = (e: globalThis.KeyboardEvent) => {
			if (e.key !== "Escape") return;
			e.preventDefault();
			e.stopPropagation();
			onClose();
		};
		window.addEventListener("keydown", onWindowKeyDown, true);
		return () => window.removeEventListener("keydown", onWindowKeyDown, true);
	}, [open, scopeMenuOpen, onClose]);

	const selectedKey = useMemo(() => {
		const sel = resolveHistorySelection(stage, result, selected);
		if (!sel) return null;
		return sel.kind === "prompt"
			? `p:${sel.hit.sessionId}:${sel.hit.messageIndex ?? sel.hit.timestamp}`
			: `m:${sel.hit.sessionId}:${sel.hit.messageIndex}`;
	}, [stage, result, selected]);

	useEffect(() => {
		if (selectedKey === null) return;
		resultsRef.current
			?.querySelector('[data-selected="true"]')
			?.scrollIntoView({ block: "nearest" });
	}, [selectedKey]);

	if (!open) return null;

	const onKeyDown = (e: KeyboardEvent<HTMLInputElement>) => {
		if (e.key === "ArrowDown") {
			e.preventDefault();
			onMoveSelection(1);
			return;
		}
		if (e.key === "ArrowUp") {
			e.preventDefault();
			onMoveSelection(-1);
			return;
		}
		if (e.key === "Tab") {
			e.preventDefault();
			onToggleStage();
			return;
		}
		if (e.key === "Enter") {
			e.preventDefault();
			const item = resolveHistorySelection(stage, result, selected);
			if (!item) return;
			if (item.kind === "prompt" && !e.shiftKey) {
				if (e.metaKey || e.ctrlKey) onInsertAndSend(item.hit);
				else onInsert(item.hit);
				return;
			}
			const target = jumpTarget(item.hit);
			if (target) onOpenMessage(target);
		}
	};

	const promptCount = result ? Math.min(result.prompts.length, result.promptTotal) : 0;
	const messageCount = result ? Math.min(result.messages.length, result.messageTotal) : 0;
	const hasResults =
		!!result && (result.prompts.length > 0 || (stage === "zoomed" && result.messages.length > 0));
	const isEmpty = !!result && !result.indexing && !hasResults;

	const selectedItem = resolveHistorySelection(stage, result, selected);
	const selectedProjectAreaName = selectedItem?.hit.projectId
		? projectAreaNames[selectedItem.hit.projectId]
		: undefined;

	const resultsBody = error ? (
		<div data-testid="history-error" className="p-md text-center text-feedback-error tr-text-ui">
			search unavailable
		</div>
	) : !result ? null : (
		<>
			{result.indexing ? (
				<div
					data-testid="history-indexing"
					className="px-sm py-1 text-center text-text-muted tr-text-metadata"
				>
					indexing history…
				</div>
			) : null}
			{result.incomplete ? (
				<div className="px-sm py-1 text-center text-feedback-warning tr-text-metadata">
					some history could not be indexed
				</div>
			) : null}
			{hasResults ? (
				<div className="flex flex-col gap-xs p-xs">
					{result.prompts.length > 0 ? (
						<div className="flex flex-col gap-0.5">
							<div className="flex items-center justify-between px-sm py-0.5 tr-text-eyebrow text-text-muted">
								<span>Prompts</span>
								<span data-testid="history-counts">
									{promptCount}/{result.promptTotal}
								</span>
							</div>
							{result.prompts.map((hit, i) => (
								<PromptRow
									key={`${hit.sessionId}:${hit.messageIndex}`}
									hit={hit}
									query={query}
									scope={scope}
									projectAreaName={hit.projectId ? projectAreaNames[hit.projectId] : undefined}
									isSelected={i === selected}
									onPick={() => onInsert(hit)}
									onOpenMessage={onOpenMessage}
									onDeleteChat={onDeleteChat}
								/>
							))}
						</div>
					) : null}
					{stage === "zoomed" && result.messages.length > 0 ? (
						<div className="flex flex-col gap-0.5">
							<div className="flex items-center justify-between px-sm py-0.5 tr-text-eyebrow text-text-muted">
								<span>Messages</span>
								<span data-testid="history-counts">
									{messageCount}/{result.messageTotal}
								</span>
							</div>
							{result.messages.map((hit, i) => (
								<MessageRow
									key={`${hit.sessionId}:${hit.messageIndex}`}
									hit={hit}
									query={query}
									isSelected={result.prompts.length + i === selected}
									onPick={() => {
										const target = jumpTarget(hit);
										if (target) onOpenMessage(target);
									}}
									onDeleteChat={onDeleteChat}
								/>
							))}
						</div>
					) : null}
				</div>
			) : isEmpty ? (
				<div className="p-md text-center text-text-muted tr-text-ui">no matches</div>
			) : null}
		</>
	);

	return (
		<div
			data-testid="history-overlay"
			data-stage={stage}
			className="absolute bottom-full left-sm right-sm mb-xs flex flex-col overflow-hidden rounded-[var(--radius-lg)] border border-border-default bg-container-elevated-bg shadow-[var(--shadow-md)]"
		>
			<div className="flex items-center gap-sm border-b border-border-default p-sm">
				<input
					ref={inputRef}
					data-testid="history-query"
					value={query}
					onChange={(e) => onQueryChange(e.target.value)}
					onKeyDown={onKeyDown}
					placeholder="Search prompts and conversations…"
					className="min-w-0 flex-1 bg-transparent tr-text-ui text-text-default outline-none placeholder:text-text-muted"
				/>
				<DropdownMenu open={scopeMenuOpen} onOpenChange={setScopeMenuOpen}>
					<DropdownMenuTrigger
						data-testid="history-scope"
						data-scope={scope.kind}
						className="flex shrink-0 items-center gap-xs rounded-full border border-border-default bg-container-project-bg px-sm py-0.5 text-text-muted tr-text-metadata outline-none hover:bg-control-bg-hovered"
					>
						<span>{SCOPE_LABELS[scope.kind]}</span>
						<span className="text-text-muted">⌃R</span>
					</DropdownMenuTrigger>
					<DropdownMenuContent
						align="end"
						onCloseAutoFocus={(e) => {
							e.preventDefault();
							inputRef.current?.focus();
						}}
					>
						{SCOPE_ORDER.map((kind) => (
							<DropdownMenuItem
								key={kind}
								data-testid="history-scope-option"
								data-scope={kind}
								onSelect={() => onSetScope(kind)}
							>
								<Check className={kind === scope.kind ? "size-3.5" : "size-3.5 invisible"} />
								<span>{SCOPE_MENU_LABELS[kind]}</span>
							</DropdownMenuItem>
						))}
					</DropdownMenuContent>
				</DropdownMenu>
			</div>
			{stage === "zoomed" ? (
				<div className="flex flex-col overflow-hidden md:flex-row">
					<div
						ref={resultsRef}
						data-testid="history-results"
						className="max-h-[37.5vh] overflow-y-auto md:max-h-[75vh] md:w-[55%]"
					>
						{resultsBody}
					</div>
					<HistoryPreview
						item={selectedItem}
						query={query}
						projectAreaName={selectedProjectAreaName}
						className="max-h-[37.5vh] border-border-default border-t md:max-h-[75vh] md:w-[45%] md:border-t-0 md:border-l"
					/>
				</div>
			) : (
				<div
					ref={resultsRef}
					data-testid="history-results"
					className="max-h-[40vh] overflow-y-auto"
				>
					{resultsBody}
				</div>
			)}
			{stage === "compact" && !error && result && !result.indexing && result.messageTotal > 0 ? (
				<button
					type="button"
					data-testid="history-expand-hint"
					onClick={onToggleStage}
					className="border-t border-border-default p-xs text-center text-text-muted tr-text-metadata hover:bg-control-bg-hovered"
				>
					{result.messageTotal} matches in conversations · ⇥ expand
				</button>
			) : null}
		</div>
	);
}

// gooseberry/webui/src/chat/history/history-overlay.svelte
<script lang="ts">
import type { HistoryScope, MessageHit, PromptHit } from "@gooseberry/contracts";
import { mewa } from "../../../vendor/mewa-svelte/index.js";
import { behavior as dropdownBehavior } from "../../../vendor/mewa-ui/components/dropdown-menu.js";
import Icon from "../../components/icon.svelte";
import { activateCheckableMenuItem } from "../../components/menu-keyboard";
import { relativeTime } from "../../lib";
import {
	type ChatLocationRequest,
	type HistorySearchState,
	highlightHistoryText,
	historyOptionKey,
	historySelectionAnnouncement,
	jumpTarget,
	resolveHistorySelection,
	SCOPE_ORDER,
} from "./history-search";

const SCOPE_LABELS: Record<HistoryScope["kind"], string> = {
	chat: "Chat",
	project: "Project",
	all: "All",
};
const SCOPE_MENU_LABELS: Record<HistoryScope["kind"], string> = {
	chat: "This chat",
	project: "Project",
	all: "Everywhere",
};

export interface HistoryOverlayProps {
	state: HistorySearchState;
	projectAreaNames: Record<string, string>;
	onQueryChange: (query: string) => void;
	onToggleStage: () => void;
	onMoveSelection: (delta: number) => void;
	onClose: () => void;
	onInsert: (hit: PromptHit) => void;
	onInsertAndSend: (hit: PromptHit) => void;
	onOpenMessage: (target: ChatLocationRequest) => void;
	onDeleteChat: (projectAreaId: string, sessionId: string) => void;
	deleteUnavailableReason?: string | undefined;
	onSetScope: (kind: HistoryScope["kind"]) => void;
}

let {
	state: historyState,
	projectAreaNames,
	onQueryChange,
	onToggleStage,
	onMoveSelection,
	onClose,
	onInsert,
	onInsertAndSend,
	onOpenMessage,
	onDeleteChat,
	deleteUnavailableReason,
	onSetScope,
}: HistoryOverlayProps = $props();

let input = $state<HTMLInputElement>();
let resultsElement = $state<HTMLDivElement>();
let scopeMenu = $state<HTMLElement>();
let scopeMenuOpen = $state(false);
let focusedOpen = false;
const componentId = $props.id();
const resultsId = `history-results-${componentId}`;
const selectedStatusId = `${resultsId}-selection`;
const scopeMenuId = `history-scope-${componentId}`;

let selectedItem = $derived(
	resolveHistorySelection(historyState.stage, historyState.result, historyState.selected),
);
let selectedKey = $derived(selectedItem ? historyOptionKey(selectedItem) : null);
let selectedProjectAreaName = $derived(
	selectedItem?.hit.projectId ? projectAreaNames[selectedItem.hit.projectId] : undefined,
);
let promptCount = $derived(
	historyState.result
		? Math.min(historyState.result.prompts.length, historyState.result.promptTotal)
		: 0,
);
let messageCount = $derived(
	historyState.result
		? Math.min(historyState.result.messages.length, historyState.result.messageTotal)
		: 0,
);
let hasResults = $derived(
	!!historyState.result &&
		(historyState.result.prompts.length > 0 ||
			(historyState.stage === "zoomed" && historyState.result.messages.length > 0)),
);
let isEmpty = $derived(!!historyState.result && !historyState.result.indexing && !hasResults);
let selectedAnnouncement = $derived(
	historySelectionAnnouncement(historyState.stage, historyState.result, historyState.selected),
);

$effect(() => {
	if (!historyState.open) {
		focusedOpen = false;
		return;
	}
	if (focusedOpen || !input) return;
	focusedOpen = true;
	queueMicrotask(() => {
		if (!input?.isConnected) return;
		input.focus();
		input.select();
	});
});

$effect(() => {
	if (!historyState.open) return;
	const handleEscape = (event: KeyboardEvent) => {
		if (event.key !== "Escape" || scopeMenuOpen) return;
		event.preventDefault();
		event.stopPropagation();
		onClose();
	};
	window.addEventListener("keydown", handleEscape, true);
	return () => window.removeEventListener("keydown", handleEscape, true);
});

$effect(() => {
	void selectedKey;
	if (!resultsElement) return;
	resultsElement.querySelector('[data-selected="true"]')?.scrollIntoView({ block: "nearest" });
});

function handleSearchKeydown(event: KeyboardEvent): void {
	if (event.key === "ArrowDown") {
		event.preventDefault();
		onMoveSelection(1);
		return;
	}
	if (event.key === "ArrowUp") {
		event.preventDefault();
		onMoveSelection(-1);
		return;
	}
	if (event.key === "Tab") {
		event.preventDefault();
		onToggleStage();
		return;
	}
	if (event.key !== "Enter") return;
	event.preventDefault();
	const item = resolveHistorySelection(
		historyState.stage,
		historyState.result,
		historyState.selected,
	);
	if (!item) return;
	if (item.kind === "prompt" && !event.shiftKey) {
		if (event.metaKey || event.ctrlKey) onInsertAndSend(item.hit);
		else onInsert(item.hit);
		return;
	}
	const target = jumpTarget(item.hit);
	if (target) onOpenMessage(target);
}

function messageCrumb(hit: MessageHit): string {
	return `${hit.sessionTitle || hit.cwd.split("/").pop() || "session"} · ${hit.role} · ${relativeTime(hit.timestamp)}`;
}

function promptCrumb(hit: PromptHit, projectAreaName: string | undefined): string {
	return [
		hit.sessionTitle,
		hit.projectId ? (projectAreaName ?? "projectArea") : undefined,
		relativeTime(hit.timestamp),
	]
		.filter((part): part is string => !!part)
		.join(" · ");
}

function selectScope(kind: HistoryScope["kind"]): void {
	onSetScope(kind);
	scopeMenu?.hidePopover();
}
</script>

{#snippet Highlight(text: string, query: string)}
	{#each highlightHistoryText(text, query) as part (part.key)}
		{#if part.highlighted}
			<mark class="rounded-[var(--radius-xs)] bg-primary-soft text-text-default">{part.text}</mark>
		{:else}
			<span>{part.text}</span>
		{/if}
	{/each}
{/snippet}

{#snippet DeleteChatButton(projectAreaId: string | undefined, sessionId: string, isSelected: boolean)}
	{#if projectAreaId}
		<button
			type="button"
			data-testid="history-delete-chat"
			aria-label={deleteUnavailableReason
				? `Move chat to trash: ${deleteUnavailableReason}`
				: "Move chat to trash"}
			title={deleteUnavailableReason ?? "Move chat to trash"}
			disabled={!!deleteUnavailableReason}
			onclick={(event) => {
				event.stopPropagation();
				onDeleteChat(projectAreaId, sessionId);
			}}
			class={`flex shrink-0 items-center justify-center rounded-[var(--radius-sm)] p-xs text-text-muted opacity-0 transition hover:bg-container-elevated-bg hover:text-feedback-error group-hover:opacity-100 ${isSelected ? "opacity-100" : ""}`}
		>
			<Icon name="trash-2" size={14} />
		</button>
	{/if}
{/snippet}

{#snippet PromptRow(hit: PromptHit, index: number)}
	{@const firstLine = hit.text.split("\n")[0] ?? hit.text}
	{@const isSelected = index === historyState.selected}
	{@const showChip = (historyState.scope.kind === "project" || historyState.scope.kind === "all") && !!hit.projectId}
	{@const target = jumpTarget(hit)}
	<li
		data-testid="history-item"
		data-kind="prompt"
		data-selected={isSelected}
		id={`${resultsId}-option-p:${hit.sessionId}:${hit.messageIndex ?? hit.timestamp}`}
		aria-current={isSelected}
		class={`group flex w-full items-center gap-xs rounded-[var(--radius-sm)] border-l-2 py-xs pl-sm pr-xs text-left tr-text-ui ${isSelected ? "border-l-primary bg-control-bg-selected text-text-default" : "border-l-transparent text-text-muted"}`}
	>
		<button type="button" onclick={() => onInsert(hit)} class="flex min-w-0 flex-1 items-center gap-sm overflow-hidden text-left">
			<span class="min-w-0 flex-1 overflow-hidden whitespace-nowrap text-ellipsis">
				{@render Highlight(firstLine, historyState.query)}
			</span>
			{#if showChip}
				<span class="shrink-0 rounded-full border border-border-default bg-container-project-bg px-xs text-text-muted tr-text-metadata">
					{hit.projectId ? (projectAreaNames[hit.projectId] ?? "projectArea") : "projectArea"}
				</span>
			{/if}
			<span class="shrink-0 text-text-muted tr-text-metadata">{relativeTime(hit.timestamp)}</span>
		</button>
		{#if target}
			{#if isSelected}<span data-testid="history-jump-shortcut" class="shrink-0 text-text-muted tr-text-metadata">⇧⏎</span>{/if}
			<button
				type="button"
				data-testid="history-jump"
				aria-label="Go to chat"
				title="⇧⏎ go to chat"
				onclick={(event) => { event.stopPropagation(); onOpenMessage(target); }}
				class={`flex shrink-0 items-center justify-center rounded-[var(--radius-sm)] p-xs text-text-muted opacity-0 transition hover:bg-container-elevated-bg hover:text-text-default group-hover:opacity-100 ${isSelected ? "opacity-100" : ""}`}
			>
				<Icon name="corner-up-right" size={14} />
			</button>
		{/if}
		{@render DeleteChatButton(hit.projectId, hit.sessionId, isSelected)}
	</li>
{/snippet}

{#snippet MessageRow(hit: MessageHit, index: number)}
	{@const isSelected = historyState.result!.prompts.length + index === historyState.selected}
	{@const unmapped = !hit.projectId}
	<li
		data-testid="history-item"
		data-kind="message"
		data-selected={isSelected}
		id={`${resultsId}-option-m:${hit.sessionId}:${hit.messageIndex}`}
		aria-current={isSelected}
		class={`group flex w-full items-center gap-xs rounded-[var(--radius-sm)] border-l-2 pr-xs tr-text-ui ${isSelected ? "border-l-primary bg-control-bg-selected text-text-default" : "border-l-transparent text-text-muted"}`}
	>
		<button
			type="button"
			disabled={unmapped}
			onclick={() => { const target = jumpTarget(hit); if (target) onOpenMessage(target); }}
			class="flex min-w-0 flex-1 flex-col gap-0.5 px-sm py-xs text-left disabled:cursor-default"
		>
			<span class="flex items-center gap-xs text-text-muted tr-text-metadata">
				<span class="truncate">{hit.sessionTitle || hit.cwd.split("/").pop() || "session"}</span>
				<span>·</span><span>{hit.role}</span><span>·</span><span>{relativeTime(hit.timestamp)}</span>
				{#if unmapped}<span>· not a gooseberry projectArea</span>{/if}
			</span>
			<span class="overflow-hidden whitespace-nowrap text-ellipsis">{@render Highlight(hit.snippet, historyState.query)}</span>
		</button>
		{@render DeleteChatButton(hit.projectId, hit.sessionId, isSelected)}
	</li>
{/snippet}

{#snippet ResultsBody()}
	{#if historyState.error}
		<div data-testid="history-error" class="p-md text-center text-feedback-error tr-text-ui">search unavailable</div>
	{:else if historyState.result}
		{#if historyState.result.indexing}
			<div data-testid="history-indexing" class="px-sm py-1 text-center text-text-muted tr-text-metadata">indexing history…</div>
		{/if}
		{#if historyState.result.incomplete}
			<div class="px-sm py-1 text-center text-feedback-warning tr-text-metadata">some history could not be indexed</div>
		{/if}
		{#if hasResults}
			<div class="flex flex-col gap-xs p-xs">
				{#if historyState.result.prompts.length > 0}
					<div class="flex flex-col gap-0.5">
						<div class="flex items-center justify-between px-sm py-0.5 tr-text-eyebrow text-text-muted">
							<span>Prompts</span><span data-testid="history-counts">{promptCount}/{historyState.result.promptTotal}</span>
						</div>
						<ul aria-label="Prompt history results" class="flex flex-col gap-0.5">
							{#each historyState.result.prompts as hit, index (`${hit.sessionId}:${hit.messageIndex}`)}
								{@render PromptRow(hit, index)}
							{/each}
						</ul>
					</div>
				{/if}
				{#if historyState.stage === "zoomed" && historyState.result.messages.length > 0}
					<div class="flex flex-col gap-0.5">
						<div class="flex items-center justify-between px-sm py-0.5 tr-text-eyebrow text-text-muted">
							<span>Messages</span><span data-testid="history-counts">{messageCount}/{historyState.result.messageTotal}</span>
						</div>
						<ul aria-label="Conversation history results" class="flex flex-col gap-0.5">
							{#each historyState.result.messages as hit, index (`${hit.sessionId}:${hit.messageIndex}`)}
								{@render MessageRow(hit, index)}
							{/each}
						</ul>
					</div>
				{/if}
			</div>
		{:else if isEmpty}
			<div class="p-md text-center text-text-muted tr-text-ui">no matches</div>
		{/if}
	{/if}
{/snippet}

{#if historyState.open}
	<div
		data-testid="history-overlay"
		data-stage={historyState.stage}
		class="absolute bottom-full left-sm right-sm mb-xs flex flex-col overflow-hidden rounded-[var(--radius-lg)] border border-border-default bg-container-elevated-bg shadow-[var(--shadow-md)]"
	>
		<div class="flex items-center gap-sm border-b border-border-default p-sm">
			<input
				bind:this={input}
				type="search"
				data-testid="history-query"
				aria-controls={resultsId}
				aria-describedby={selectedStatusId}
				value={historyState.query}
				oninput={(event) => onQueryChange(event.currentTarget.value)}
				onkeydown={handleSearchKeydown}
				placeholder="Search prompts and conversations…"
				class="min-w-0 flex-1 bg-transparent tr-text-ui text-text-default outline-none placeholder:text-text-muted"
			/>
			<span id={selectedStatusId} role="status" aria-live="polite" class="sr-only">{selectedAnnouncement}</span>
			<span class="contents" {@attach mewa(dropdownBehavior)}>
				<button
					type="button"
					data-dropdown-menu-trigger={scopeMenuId}
					aria-haspopup="menu"
					aria-controls={scopeMenuId}
					aria-expanded="false"
					data-testid="history-scope"
					data-scope={historyState.scope.kind}
					class="flex shrink-0 items-center gap-xs rounded-full border border-border-default bg-container-project-bg px-sm py-0.5 text-text-muted tr-text-metadata outline-none hover:bg-control-bg-hovered"
				>
					<span>{SCOPE_LABELS[historyState.scope.kind]}</span><span class="text-text-muted">⌃R</span>
				</button>
				<div
					bind:this={scopeMenu}
					id={scopeMenuId}
					popover="auto"
					role="menu"
					class="dropdown-menu-content history-scope-menu"
					ontoggle={(event) => {
						scopeMenuOpen = event.newState === "open";
						if (!scopeMenuOpen) queueMicrotask(() => input?.focus());
					}}
				>
					{#each SCOPE_ORDER as kind}
						<button
							type="button"
							role="menuitemradio"
							aria-checked={kind === historyState.scope.kind}
							data-testid="history-scope-option"
							data-scope={kind}
							class="dropdown-menu-item"
							onkeydown={activateCheckableMenuItem}
							onclick={() => selectScope(kind)}
						>
							<Icon name="check" size={14} class={kind === historyState.scope.kind ? "" : "invisible"} />
							<span>{SCOPE_MENU_LABELS[kind]}</span>
						</button>
					{/each}
				</div>
			</span>
		</div>
		{#if deleteUnavailableReason}
			<p class="border-border-default border-b px-sm py-xs text-text-muted tr-text-metadata">{deleteUnavailableReason}</p>
		{/if}
		{#if historyState.stage === "zoomed"}
			<div class="flex flex-col overflow-hidden md:flex-row">
				<div bind:this={resultsElement} data-testid="history-results" id={resultsId} class="max-h-[37.5vh] overflow-y-auto md:max-h-[75vh] md:w-[55%]">
					{@render ResultsBody()}
				</div>
				<div data-testid="history-preview" class="flex max-h-[37.5vh] flex-col overflow-hidden border-border-default border-t md:max-h-[75vh] md:w-[45%] md:border-t-0 md:border-l">
					{#if selectedItem}
						<div class="min-h-0 flex-1 overflow-y-auto whitespace-pre-wrap break-words p-sm tr-text-ui text-text-default">{@render Highlight(selectedItem.hit.text, historyState.query)}</div>
						<div class="shrink-0 border-t border-border-default px-sm py-xs text-text-muted tr-text-metadata">
							{selectedItem.kind === "prompt" ? promptCrumb(selectedItem.hit, selectedProjectAreaName) : messageCrumb(selectedItem.hit)}
						</div>
					{/if}
				</div>
			</div>
		{:else}
			<div bind:this={resultsElement} data-testid="history-results" id={resultsId} class="max-h-[40vh] overflow-y-auto">
				{@render ResultsBody()}
			</div>
		{/if}
		{#if historyState.stage === "compact" && !historyState.error && historyState.result && !historyState.result.indexing && historyState.result.messageTotal > 0}
			<button type="button" data-testid="history-expand-hint" onclick={onToggleStage} class="border-t border-border-default p-xs text-center text-text-muted tr-text-metadata hover:bg-control-bg-hovered">
				{historyState.result.messageTotal} matches in conversations · ⇥ expand
			</button>
		{/if}
	</div>
{/if}

<style>
	.history-scope-menu { left: auto; right: anchor(right); }
</style>
