// gooseberry/webui/src/chat/session/session-model-controls.tsx
import type { ProviderStatus, ThinkingLevel, WireModel } from "@gooseberry/contracts";
import { useCallback, useEffect, useId, useMemo, useRef, useState } from "react";
import { errorText, getTransport } from "../../connection";
import { toast, useAppStore } from "../../store";

function modelKey(model: Pick<WireModel, "provider" | "id">): string {
	return `${model.provider}\u0000${model.id}`;
}

export function sessionSelectableModels(
	models: readonly WireModel[],
	providers: readonly ProviderStatus[],
): WireModel[] {
	const availableProviders = new Set(
		providers
			.filter((provider) => provider.configured && provider.available !== false)
			.map((provider) => provider.id),
	);
	return models.filter(
		(model) => availableProviders.has(model.provider) && model.available && !model.hidden,
	);
}

export function thinkingLevelsForCurrent(
	level: ThinkingLevel,
	reported: readonly ThinkingLevel[],
): ThinkingLevel[] {
	return reported.includes(level) ? [...reported] : [level, ...reported];
}

export function firstModelForProvider(
	models: readonly WireModel[],
	providerId: string,
): WireModel | null {
	return models.find((model) => model.provider === providerId) ?? null;
}

export function modelsForSelectedProvider(
	models: readonly WireModel[],
	providerId: string,
): WireModel[] {
	return models.filter((model) => model.provider === providerId);
}

export function SessionModelControls({
	sessionId,
	model,
	thinkingLevel,
	isStreaming,
}: {
	sessionId: string;
	model: WireModel | null;
	thinkingLevel: ThinkingLevel;
	isStreaming: boolean;
}) {
	const [catalog, setCatalog] = useState<WireModel[]>([]);
	const [providers, setProviders] = useState<ProviderStatus[]>([]);
	const [reportedThinkingLevels, setReportedThinkingLevels] = useState<ThinkingLevel[]>([]);
	const [loading, setLoading] = useState(true);
	const [busy, setBusy] = useState<"model" | "thinking" | null>(null);
	const loadSequence = useRef(0);
	const providerVersion = useAppStore((state) => state.providerVersion);
	const providerLabelId = useId();
	const modelLabelId = useId();
	const thinkingLabelId = useId();

	useEffect(() => {
		void providerVersion;
		const sequence = ++loadSequence.current;
		setLoading(true);
		void Promise.all([
			getTransport().request("model.list", {}),
			getTransport().request("provider.status", {}),
			getTransport().request("model.thinkingLevels", { sessionId }),
		])
			.then(([nextModels, report, thinking]) => {
				if (sequence !== loadSequence.current) return;
				setCatalog(nextModels);
				setProviders(report.providers);
				setReportedThinkingLevels(thinking.levels);
			})
			.catch((error) => {
				if (sequence !== loadSequence.current) return;
				setCatalog([]);
				setProviders([]);
				setReportedThinkingLevels([]);
				toast.error(errorText(error), "Couldn't load session model controls");
			})
			.finally(() => {
				if (sequence === loadSequence.current) setLoading(false);
			});
	}, [providerVersion, sessionId]);

	const models = useMemo(() => sessionSelectableModels(catalog, providers), [catalog, providers]);
	const providerIds = useMemo(
		() => [...new Set(models.map((candidate) => candidate.provider))],
		[models],
	);
	const providerNames = useMemo(
		() => new Map(providers.map((provider) => [provider.id, provider.name])),
		[providers],
	);
	const selectedModel = model ?? null;
	const currentModelSelectable = selectedModel
		? models.some((candidate) => modelKey(candidate) === modelKey(selectedModel))
		: false;
	const currentProviderSelectable = selectedModel
		? providerIds.includes(selectedModel.provider)
		: false;
	const selectedProvider = selectedModel?.provider ?? "";
	const providerModels = useMemo(
		() => modelsForSelectedProvider(models, selectedProvider),
		[models, selectedProvider],
	);
	const thinkingLevels = thinkingLevelsForCurrent(thinkingLevel, reportedThinkingLevels);
	const modelControlsDisabled = loading || isStreaming || busy !== null || models.length === 0;
	const thinkingDisabled = isStreaming || busy !== null;

	const changeModel = useCallback(
		async (nextModel: WireModel) => {
			if (model && modelKey(nextModel) === modelKey(model)) return;
			setBusy("model");
			try {
				try {
					await getTransport().request("session.setModel", { sessionId, model: nextModel });
					useAppStore.getState().setCurrentModel(sessionId, nextModel);
				} catch (error) {
					toast.error(errorText(error), "Couldn't change the session model");
					return;
				}
				try {
					const thinking = await getTransport().request("model.thinkingLevels", { sessionId });
					setReportedThinkingLevels(thinking.levels);
					const { level } = await getTransport().request("model.clampThinking", {
						sessionId,
						level: thinkingLevel,
					});
					if (level === thinkingLevel) return;
					await getTransport().request("session.setThinkingLevel", { sessionId, level });
					useAppStore.getState().setThinkingLevel(sessionId, level);
				} catch (error) {
					toast.error(errorText(error), "Couldn't update thinking after changing the model");
				}
			} finally {
				setBusy(null);
			}
		},
		[model, sessionId, thinkingLevel],
	);

	const changeThinking = useCallback(
		async (level: ThinkingLevel) => {
			if (level === thinkingLevel) return;
			setBusy("thinking");
			try {
				const clamped = await getTransport().request("model.clampThinking", { sessionId, level });
				if (clamped.level === thinkingLevel) return;
				await getTransport().request("session.setThinkingLevel", {
					sessionId,
					level: clamped.level,
				});
				useAppStore.getState().setThinkingLevel(sessionId, clamped.level);
			} catch (error) {
				toast.error(errorText(error), "Couldn't change the thinking level");
			} finally {
				setBusy(null);
			}
		},
		[sessionId, thinkingLevel],
	);

	return (
		<div
			data-testid="session-model-controls"
			aria-busy={loading || busy !== null}
			className="flex min-w-0 flex-wrap items-center gap-xs"
		>
			<label className="flex min-w-0 items-center gap-2xs">
				<span id={providerLabelId} className="sr-only">
					Provider
				</span>
				<select
					data-testid="session-provider-select"
					aria-labelledby={providerLabelId}
					value={selectedProvider}
					disabled={modelControlsDisabled}
					onChange={(event) => {
						const next = firstModelForProvider(models, event.target.value);
						if (next) void changeModel(next);
					}}
					className="min-w-0 max-w-28 rounded-[var(--radius-sm)] border border-border-default bg-control-bg px-xs py-0.5 text-text-default tr-text-metadata outline-none hover:bg-control-bg-hovered focus-visible:ring-2 focus-visible:ring-primary disabled:text-text-muted"
				>
					{selectedModel && !currentProviderSelectable ? (
						<option value={selectedModel.provider} disabled>
							{providerNames.get(selectedModel.provider) ?? selectedModel.provider} (current)
						</option>
					) : null}
					<option value="" disabled>
						{loading ? "Loading providers…" : "No providers"}
					</option>
					{providerIds.map((providerId) => (
						<option key={providerId} value={providerId}>
							{providerNames.get(providerId) ?? providerId}
						</option>
					))}
				</select>
			</label>
			<label className="flex min-w-0 items-center gap-2xs">
				<span id={modelLabelId} className="sr-only">
					Model
				</span>
				<select
					data-testid="session-model-select"
					aria-labelledby={modelLabelId}
					value={selectedModel ? modelKey(selectedModel) : ""}
					disabled={modelControlsDisabled}
					onChange={(event) => {
						const next = models.find((candidate) => modelKey(candidate) === event.target.value);
						if (next) void changeModel(next);
					}}
					className="min-w-0 max-w-44 rounded-[var(--radius-sm)] border border-border-default bg-control-bg px-xs py-0.5 text-text-default tr-text-metadata outline-none hover:bg-control-bg-hovered focus-visible:ring-2 focus-visible:ring-primary disabled:text-text-muted"
				>
					{selectedModel && !currentModelSelectable ? (
						<option value={modelKey(selectedModel)} disabled>
							{selectedModel.name || selectedModel.id} (current)
						</option>
					) : null}
					<option value="" disabled>
						{loading ? "Loading models…" : "No available models"}
					</option>
					{providerModels.map((candidate) => (
						<option key={modelKey(candidate)} value={modelKey(candidate)}>
							{candidate.name || candidate.id}
						</option>
					))}
				</select>
			</label>
			<label className="flex min-w-0 items-center gap-2xs">
				<span id={thinkingLabelId} className="sr-only">
					Thinking
				</span>
				<select
					data-testid="session-thinking-select"
					aria-labelledby={thinkingLabelId}
					value={thinkingLevel}
					disabled={thinkingDisabled}
					onChange={(event) => void changeThinking(event.target.value)}
					className="min-w-0 max-w-24 rounded-[var(--radius-sm)] border border-border-default bg-control-bg px-xs py-0.5 text-text-default tr-text-metadata outline-none hover:bg-control-bg-hovered focus-visible:ring-2 focus-visible:ring-primary disabled:text-text-muted"
				>
					{thinkingLevels.map((level) => (
						<option key={level} value={level}>
							{level}
						</option>
					))}
				</select>
			</label>
		</div>
	);
}

// gooseberry/webui/src/chat/session/session-model-controls.svelte
<script lang="ts">
import type { ProviderStatus, ThinkingLevel, WireModel } from "@gooseberry/contracts";
import { errorText, getTransport } from "../../connection";
import { appStore, appStoreApi } from "../../store";
import { hiddenModelRevision } from "../../settings/state";
import {
	firstModelForProvider,
	modelKey,
	modelsForSelectedProvider,
	sessionSelectableModels,
	thinkingLevelsForCurrent,
} from "./session-model";

interface Props {
	sessionId: string;
	model: WireModel | null;
	thinkingLevel: ThinkingLevel;
	isStreaming: boolean;
}

let { sessionId, model, thinkingLevel, isStreaming }: Props = $props();
let catalog = $state<WireModel[]>([]);
let providers = $state<ProviderStatus[]>([]);
let reportedThinkingLevels = $state<ThinkingLevel[]>([]);
let loading = $state(true);
let busy = $state<"model" | "thinking" | null>(null);
let loadSequence = 0;
const componentId = $props.id();
const providerLabelId = `session-provider-${componentId}`;
const modelLabelId = `session-model-${componentId}`;
const thinkingLabelId = `session-thinking-${componentId}`;
let providerVersion = $derived($appStore.providerVersion);
let visibilityRevision = $derived(hiddenModelRevision($appStore.config));

let models = $derived(sessionSelectableModels(catalog, providers));
let providerIds = $derived([...new Set(models.map((candidate) => candidate.provider))]);
let providerNames = $derived(new Map(providers.map((provider) => [provider.id, provider.name])));
let selectedModel = $derived(model ?? null);
let currentModelSelectable = $derived(
	selectedModel
		? models.some((candidate) => modelKey(candidate) === modelKey(selectedModel))
		: false,
);
let currentProviderSelectable = $derived(
	selectedModel ? providerIds.includes(selectedModel.provider) : false,
);
let selectedProvider = $derived(selectedModel?.provider ?? "");
let providerModels = $derived(modelsForSelectedProvider(models, selectedProvider));
let thinkingLevels = $derived(thinkingLevelsForCurrent(thinkingLevel, reportedThinkingLevels));
let modelControlsDisabled = $derived(
	loading || isStreaming || busy !== null || models.length === 0,
);
let thinkingDisabled = $derived(isStreaming || busy !== null);

function notifyError(cause: unknown, title: string): void {
	appStoreApi.getState().pushToast({ variant: "error", message: errorText(cause), title });
}

$effect(() => {
	const id = sessionId;
	void providerVersion;
	void visibilityRevision;
	const sequence = ++loadSequence;
	loading = true;
	void Promise.all([
		getTransport().request("model.list", {}),
		getTransport().request("provider.status", {}),
		getTransport().request("model.thinkingLevels", { sessionId: id }),
	])
		.then(([nextModels, report, thinking]) => {
			if (sequence !== loadSequence) return;
			catalog = nextModels;
			providers = report.providers;
			reportedThinkingLevels = thinking.levels;
		})
		.catch((cause) => {
			if (sequence !== loadSequence) return;
			catalog = [];
			providers = [];
			reportedThinkingLevels = [];
			notifyError(cause, "Couldn't load session model controls");
		})
		.finally(() => {
			if (sequence === loadSequence) loading = false;
		});
	return () => {
		if (sequence === loadSequence) loadSequence += 1;
	};
});

async function changeModel(nextModel: WireModel): Promise<void> {
	const requestedSessionId = sessionId;
	const currentModel = model;
	const requestedThinkingLevel = thinkingLevel;
	if (currentModel && modelKey(nextModel) === modelKey(currentModel)) return;
	busy = "model";
	try {
		try {
			const configRevision =
				appStoreApi.getState().sessions[requestedSessionId]?.configRevision ?? 0;
			await getTransport().request("session.setModel", {
				sessionId: requestedSessionId,
				model: nextModel,
			});
			appStoreApi.getState().setCurrentModel(requestedSessionId, nextModel, configRevision);
		} catch (cause) {
			notifyError(cause, "Couldn't change the session model");
			return;
		}
		try {
			const thinking = await getTransport().request("model.thinkingLevels", {
				sessionId: requestedSessionId,
			});
			reportedThinkingLevels = thinking.levels;
			const { level } = await getTransport().request("model.clampThinking", {
				sessionId: requestedSessionId,
				level: requestedThinkingLevel,
			});
			if (level === requestedThinkingLevel) return;
			const configRevision =
				appStoreApi.getState().sessions[requestedSessionId]?.configRevision ?? 0;
			await getTransport().request("session.setThinkingLevel", {
				sessionId: requestedSessionId,
				level,
			});
			appStoreApi.getState().setThinkingLevel(requestedSessionId, level, configRevision);
		} catch (cause) {
			notifyError(cause, "Couldn't update thinking after changing the model");
		}
	} finally {
		busy = null;
	}
}

async function changeThinking(level: ThinkingLevel): Promise<void> {
	const requestedSessionId = sessionId;
	const currentThinkingLevel = thinkingLevel;
	if (level === currentThinkingLevel) return;
	busy = "thinking";
	try {
		const clamped = await getTransport().request("model.clampThinking", {
			sessionId: requestedSessionId,
			level,
		});
		if (clamped.level === currentThinkingLevel) return;
		const configRevision = appStoreApi.getState().sessions[requestedSessionId]?.configRevision ?? 0;
		await getTransport().request("session.setThinkingLevel", {
			sessionId: requestedSessionId,
			level: clamped.level,
		});
		appStoreApi.getState().setThinkingLevel(requestedSessionId, clamped.level, configRevision);
	} catch (cause) {
		notifyError(cause, "Couldn't change the thinking level");
	} finally {
		busy = null;
	}
}
</script>

<div
	data-testid="session-model-controls"
	aria-busy={loading || busy !== null}
	class="flex min-w-0 flex-wrap items-center gap-xs"
>
	<label class="flex min-w-0 items-center gap-2xs">
		<span id={providerLabelId} class="sr-only">Provider</span>
		<select
			data-testid="session-provider-select"
			aria-labelledby={providerLabelId}
			value={selectedProvider}
			disabled={modelControlsDisabled}
			onchange={(event) => {
				const next = firstModelForProvider(models, event.currentTarget.value);
				if (next) void changeModel(next);
			}}
			class="min-w-0 max-w-28 rounded-[var(--radius-sm)] border border-border-default bg-control-bg px-xs py-0.5 text-text-default tr-text-metadata outline-none hover:bg-control-bg-hovered focus-visible:ring-2 focus-visible:ring-primary disabled:text-text-muted"
		>
			{#if selectedModel && !currentProviderSelectable}
				<option value={selectedModel.provider} disabled>{providerNames.get(selectedModel.provider) ?? selectedModel.provider} (current)</option>
			{/if}
			<option value="" disabled>{loading ? "Loading providers…" : "No providers"}</option>
			{#each providerIds as providerId (providerId)}
				<option value={providerId}>{providerNames.get(providerId) ?? providerId}</option>
			{/each}
		</select>
	</label>
	<label class="flex min-w-0 items-center gap-2xs">
		<span id={modelLabelId} class="sr-only">Model</span>
		<select
			data-testid="session-model-select"
			aria-labelledby={modelLabelId}
			value={selectedModel ? modelKey(selectedModel) : ""}
			disabled={modelControlsDisabled}
			onchange={(event) => {
				const next = models.find((candidate) => modelKey(candidate) === event.currentTarget.value);
				if (next) void changeModel(next);
			}}
			class="min-w-0 max-w-44 rounded-[var(--radius-sm)] border border-border-default bg-control-bg px-xs py-0.5 text-text-default tr-text-metadata outline-none hover:bg-control-bg-hovered focus-visible:ring-2 focus-visible:ring-primary disabled:text-text-muted"
		>
			{#if selectedModel && !currentModelSelectable}
				<option value={modelKey(selectedModel)} disabled>{selectedModel.name || selectedModel.id} (current)</option>
			{/if}
			<option value="" disabled>{loading ? "Loading models…" : "No available models"}</option>
			{#each providerModels as candidate (modelKey(candidate))}
				<option value={modelKey(candidate)}>{candidate.name || candidate.id}</option>
			{/each}
		</select>
	</label>
	<label class="flex min-w-0 items-center gap-2xs">
		<span id={thinkingLabelId} class="sr-only">Thinking</span>
		<select
			data-testid="session-thinking-select"
			aria-labelledby={thinkingLabelId}
			value={thinkingLevel}
			disabled={thinkingDisabled}
			onchange={(event) => void changeThinking(event.currentTarget.value as ThinkingLevel)}
			class="min-w-0 max-w-24 rounded-[var(--radius-sm)] border border-border-default bg-control-bg px-xs py-0.5 text-text-default tr-text-metadata outline-none hover:bg-control-bg-hovered focus-visible:ring-2 focus-visible:ring-primary disabled:text-text-muted"
		>
			{#each thinkingLevels as level (level)}<option value={level}>{level}</option>{/each}
		</select>
	</label>
</div>
