// gooseberry/webui/src/workspace/projects/project-chat-history.svelte
<script lang="ts">
import type { SessionSummary } from "@gooseberry/contracts";
import { mewa } from "../../../vendor/mewa-svelte/index.js";
import { behavior as dropdownBehavior } from "../../../vendor/mewa-ui/components/dropdown-menu.js";
import ArchiveSessionDialog from "../../chat/session/archive-session-dialog.svelte";
import RenameSessionDialog from "../../chat/session/rename-session-dialog.svelte";
import type { SessionLifecycleTarget } from "../../chat/session/session-lifecycle";
import { unsupportedLifecycleReason } from "../../chat/session/session-lifecycle";
import Button from "../../components/button.svelte";
import Icon from "../../components/icon.svelte";
import { activateCheckableMenuItem } from "../../components/menu-keyboard";
import { errorText, getTransport } from "../../connection";
import { relativeTime } from "../../lib";
import { appStore, appStoreApi, toast } from "../../store";
import { openChatInTab } from "../navigation/open-chat";
import { shouldLoadArchivedChats } from "./project-chat-history-state";

interface Props {
	projectAreaId: string;
}
let { projectAreaId }: Props = $props();
let menuOpen = $state(false);
let showArchived = $state(false);
let archived = $state<SessionSummary[]>([]);
let archivedLoading = $state(false);
let archivedError = $state(false);
let restoring = $state<string | null>(null);
let renameTarget = $state<SessionLifecycleTarget | null>(null);
let archiveTarget = $state<SessionLifecycleTarget | null>(null);
let loadSequence = 0;
let menu: HTMLElement;
const componentId = $props.id();
const menuId = `chat-history-${componentId}`;
let connectionStatus = $derived($appStore.status);
let connectionGeneration = $derived($appStore.connectionGeneration);
let closed = $derived($appStore.closedChatsByProjectArea[projectAreaId] ?? []);
let catalogVersion = $derived($appStore.sessionCatalogVersionByProjectArea[projectAreaId] ?? 0);
let canRename = $derived($appStore.agentProfile?.operations.renameSession === true);
let canArchive = $derived($appStore.agentProfile?.operations.archiveSession === true);
let canDelete = $derived($appStore.agentProfile?.operations.deleteSession === true);
let renameUnavailable = $derived(
	canRename ? undefined : unsupportedLifecycleReason($appStore.agentProfile?.name, "renaming"),
);
let archiveUnavailable = $derived(
	canArchive ? undefined : unsupportedLifecycleReason($appStore.agentProfile?.name, "archiving"),
);
let deleteUnavailable = $derived(
	canDelete ? undefined : unsupportedLifecycleReason($appStore.agentProfile?.name, "deleting"),
);
let unavailableActions = $derived(
	[renameUnavailable, archiveUnavailable, deleteUnavailable].filter(
		(reason): reason is string => !!reason,
	),
);

async function loadArchived(): Promise<void> {
	if (!canArchive || !showArchived) return;
	const sequence = ++loadSequence;
	archivedLoading = true;
	try {
		const sessions = await getTransport().request("session.list", {
			projectId: projectAreaId,
			archived: true,
		});
		if (sequence !== loadSequence) return;
		archived = sessions;
		archivedError = false;
	} catch {
		if (sequence === loadSequence) archivedError = true;
	} finally {
		if (sequence === loadSequence) archivedLoading = false;
	}
}

$effect(() => {
	void catalogVersion;
	void connectionGeneration;
	if (shouldLoadArchivedChats(menuOpen, showArchived, connectionStatus, canArchive))
		void loadArchived();
});

$effect(() => {
	if (!canRename) renameTarget = null;
	if (!canArchive) archiveTarget = null;
});

function toggleArchived(): void {
	if (showArchived) {
		loadSequence += 1;
		archivedLoading = false;
		archivedError = false;
	}
	showArchived = !showArchived;
}

function restore(sessionId: string): void {
	if (!canArchive) return;
	restoring = sessionId;
	void getTransport()
		.request("session.unarchive", { projectId: projectAreaId, sessionId })
		.then(() => {
			archived = archived.filter((session) => session.sessionId !== sessionId);
			appStoreApi
				.getState()
				.applySessionLifecycle({ projectId: projectAreaId, sessionId, operation: "unarchived" });
		})
		.catch((cause) => toast.error(errorText(cause), "Couldn't restore the chat"))
		.finally(() => {
			if (restoring === sessionId) restoring = null;
		});
}

function closeMenu(): void {
	menu?.hidePopover();
}
function remove(chat: { sessionId: string; title: string }): void {
	if (!canDelete) return;
	void getTransport()
		.request("session.delete", { projectId: projectAreaId, sessionId: chat.sessionId })
		.then(() => appStoreApi.getState().deleteChat(projectAreaId, chat.sessionId))
		.catch((cause) => {
			const state = appStoreApi.getState();
			if (
				!state.removedProjectAreaIds[projectAreaId] &&
				!state.deletedSessionsByProjectArea[projectAreaId]?.[chat.sessionId]
			) {
				toast.error(errorText(cause), "Couldn't delete the chat");
			}
		});
}
</script>

<span class="contents" {@attach mewa(dropdownBehavior)}>
	<Button
		variant="ghost"
		size="icon-sm"
		data-testid="chat-history"
		data-dropdown-menu-trigger={menuId}
		aria-haspopup="menu"
		aria-controls={menuId}
		aria-expanded="false"
		aria-label="View chat history"
		title="View chat history"
	>
		<Icon name="clock-arrow-left" size={16} />
	</Button>
	<div bind:this={menu} id={menuId} popover="auto" role="menu" class="dropdown-menu-content history-menu" ontoggle={(event) => { menuOpen = event.newState === "open"; }}>
		<div class="dropdown-menu-label">Recently closed</div>
		{#if closed.length === 0}
			<p class="px-sm py-xs text-text-muted tr-text-metadata">No recently closed chats</p>
		{:else}
			{#each closed as chat (chat.sessionId)}
				<div role="group" data-testid="closed-chat-row" class="flex items-center">
					<button type="button" role="menuitem" class="dropdown-menu-item min-w-0 flex-1" data-testid="closed-chat-item" data-session-id={chat.sessionId} onclick={() => { closeMenu(); void openChatInTab(projectAreaId, chat.sessionId); }}>
						<span class="flex-1 truncate">{chat.title}</span><span class="dropdown-menu-shortcut">{relativeTime(chat.closedAt)}</span><Icon name="rotate-ccw" size={14} />
					</button>
					<button type="button" role="menuitem" class="dropdown-menu-item shrink-0 px-xs" disabled={!canRename} title={renameUnavailable ?? "Rename chat"} aria-label={renameUnavailable ? `Rename ${chat.title}: ${renameUnavailable}` : `Rename ${chat.title}`} onclick={() => { closeMenu(); renameTarget = { projectId: projectAreaId, sessionId: chat.sessionId, title: chat.title }; }}><Icon name="pencil" size={14} /></button>
					<button type="button" role="menuitem" class="dropdown-menu-item shrink-0 px-xs" disabled={!canArchive} title={archiveUnavailable ?? "Archive chat"} aria-label={archiveUnavailable ? `Archive ${chat.title}: ${archiveUnavailable}` : `Archive ${chat.title}`} onclick={() => { closeMenu(); archiveTarget = { projectId: projectAreaId, sessionId: chat.sessionId, title: chat.title }; }}><Icon name="archive" size={14} /></button>
					<button type="button" role="menuitem" class="dropdown-menu-item shrink-0 px-xs" data-variant="destructive" data-testid="closed-chat-delete" disabled={!canDelete} title={deleteUnavailable ?? "Move chat to trash"} aria-label={deleteUnavailable ? `Move ${chat.title} to trash: ${deleteUnavailable}` : `Move ${chat.title} to trash`} onclick={() => remove(chat)}><Icon name="trash-2" size={14} /></button>
				</div>
			{/each}
		{/if}
		{#each unavailableActions as reason}<p class="max-w-[18rem] px-sm py-xs text-text-muted tr-text-metadata">{reason}</p>{/each}
		<div class="dropdown-menu-separator"></div>
		<button type="button" role="menuitemcheckbox" aria-checked={showArchived} class="dropdown-menu-item dropdown-menu-check" data-testid="chat-history-archived-toggle" disabled={!canArchive} title={archiveUnavailable} onkeydown={activateCheckableMenuItem} onclick={(event) => { event.preventDefault(); toggleArchived(); }}>
			{showArchived ? "Hide archived chats" : "Show archived chats"}
		</button>
		{#if showArchived && !canArchive}
			<p class="max-w-[18rem] px-sm py-xs text-text-muted tr-text-metadata">{archiveUnavailable}</p>
		{:else if showArchived && archivedLoading}
			<p role="status" aria-live="polite" class="px-sm py-xs text-text-muted tr-text-metadata">Loading archived chats…</p>
		{:else if showArchived && archivedError}
			<button type="button" role="menuitem" class="dropdown-menu-item" aria-label="Retry loading archived chats" onclick={() => void loadArchived()}>Couldn't load archived chats · Retry</button>
		{:else if showArchived && archived.length === 0}
			<p class="px-sm py-xs text-text-muted tr-text-metadata">No archived chats</p>
		{:else if showArchived}
			{#each archived as session (session.sessionId)}
				<button type="button" role="menuitem" class="dropdown-menu-item" disabled={restoring === session.sessionId} aria-label={restoring === session.sessionId ? `Restoring ${session.title}` : `Restore ${session.title}`} onclick={() => restore(session.sessionId)}>
					<span class="min-w-0 flex-1 truncate">{session.title}</span><span class="dropdown-menu-shortcut">{relativeTime(session.updatedAt)}</span><Icon name="archive-restore" size={14} />
				</button>
			{/each}
		{/if}
	</div>
</span>
{#if renameTarget}<RenameSessionDialog target={renameTarget} open onOpenChange={(next) => { if (!next) renameTarget = null; }} />{/if}
{#if archiveTarget}<ArchiveSessionDialog target={archiveTarget} open onOpenChange={(next) => { if (!next) archiveTarget = null; }} />{/if}

<style>
	.history-menu { left: auto; right: anchor(right); min-width: 18rem; max-height: min(32rem, 80vh); overflow: auto; }
</style>

// gooseberry/webui/src/shell/project-chat-history.tsx
import type { SessionSummary } from "@gooseberry/contracts";
import { Archive, ArchiveRestore, History, Pencil, RotateCcw, Trash2 } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import {
	DropdownMenu,
	DropdownMenuContent,
	DropdownMenuGroup,
	DropdownMenuItem,
	DropdownMenuLabel,
	DropdownMenuSeparator,
	DropdownMenuTrigger,
} from "../components/ui/dropdown-menu";
import { relativeTime } from "../lib";
import { openChatInTab } from "../panels/open-chat";
import { type ClosedChat, toast, useAppStore } from "../store";
import { errorText, getTransport } from "../transport";
import {
	ArchiveSessionDialog,
	RenameSessionDialog,
	type SessionLifecycleTarget,
} from "./session-lifecycle-controls";

export function ProjectChatHistory({ projectAreaId }: { projectAreaId: string }) {
	const closed = useAppStore(
		(state) => state.closedChatsByProjectArea[projectAreaId] ?? EMPTY_CHATS,
	);
	const catalogVersion = useAppStore(
		(state) => state.sessionCatalogVersionByProjectArea[projectAreaId] ?? 0,
	);
	const connectionGeneration = useAppStore((state) => state.connectionGeneration);
	const status = useAppStore((state) => state.status);
	const [open, setOpen] = useState(false);
	const [archived, setArchived] = useState<SessionSummary[]>([]);
	const [archivedLoading, setArchivedLoading] = useState(false);
	const [archivedError, setArchivedError] = useState(false);
	const [restoring, setRestoring] = useState<string | null>(null);
	const [renameTarget, setRenameTarget] = useState<SessionLifecycleTarget | null>(null);
	const [archiveTarget, setArchiveTarget] = useState<SessionLifecycleTarget | null>(null);
	const loadSequence = useRef(0);

	const loadArchived = useCallback(async () => {
		const sequence = ++loadSequence.current;
		setArchivedLoading(true);
		try {
			const sessions = await getTransport().request("session.list", {
				projectId: projectAreaId,
				archived: true,
			});
			if (sequence !== loadSequence.current) return;
			setArchived(sessions);
			setArchivedError(false);
		} catch {
			if (sequence === loadSequence.current) setArchivedError(true);
		} finally {
			if (sequence === loadSequence.current) setArchivedLoading(false);
		}
	}, [projectAreaId]);

	useEffect(() => {
		void catalogVersion;
		void connectionGeneration;
		if (open && status === "connected") void loadArchived();
	}, [catalogVersion, connectionGeneration, loadArchived, open, status]);

	const restore = (sessionId: string) => {
		setRestoring(sessionId);
		void getTransport()
			.request("session.unarchive", { projectId: projectAreaId, sessionId })
			.then(() => {
				setArchived((current) => current.filter((session) => session.sessionId !== sessionId));
				useAppStore.getState().applySessionLifecycle({
					projectId: projectAreaId,
					sessionId,
					operation: "unarchived",
				});
			})
			.catch((cause) => toast.error(errorText(cause), "Couldn't restore the chat"))
			.finally(() => setRestoring((current) => (current === sessionId ? null : current)));
	};

	return (
		<>
			<DropdownMenu open={open} onOpenChange={setOpen}>
				<DropdownMenuTrigger
					data-testid="chat-history"
					aria-label="View chat history"
					title="View chat history"
					className="flex w-7 shrink-0 items-center justify-center border-border-default border-l text-text-muted outline-none hover:bg-control-bg-hovered hover:text-text-default focus-visible:ring-2 focus-visible:ring-primary"
				>
					<History className="size-4" />
				</DropdownMenuTrigger>
				<DropdownMenuContent align="end" className="min-w-[18rem]">
					<DropdownMenuLabel>Recently closed</DropdownMenuLabel>
					{closed.length === 0 ? (
						<p className="px-sm py-xs text-text-muted tr-text-metadata">No recently closed chats</p>
					) : (
						closed.map((chat) => (
							<DropdownMenuGroup
								key={chat.sessionId}
								data-testid="closed-chat-row"
								className="flex items-center"
							>
								<DropdownMenuItem
									data-testid="closed-chat-item"
									data-session-id={chat.sessionId}
									onSelect={() => void openChatInTab(projectAreaId, chat.sessionId)}
									className="min-w-0 flex-1"
								>
									<span className="flex-1 truncate">{chat.title}</span>
									<span className="shrink-0 tr-text-metadata text-text-muted">
										{relativeTime(chat.closedAt)}
									</span>
									<RotateCcw className="size-3.5 shrink-0 text-text-muted" />
								</DropdownMenuItem>
								<DropdownMenuItem
									aria-label={`Rename ${chat.title}`}
									title="Rename chat"
									onSelect={() =>
										setRenameTarget({
											projectId: projectAreaId,
											sessionId: chat.sessionId,
											title: chat.title,
										})
									}
									className="shrink-0 px-xs text-text-muted"
								>
									<Pencil className="size-3.5" />
								</DropdownMenuItem>
								<DropdownMenuItem
									aria-label={`Archive ${chat.title}`}
									title="Archive chat"
									onSelect={() =>
										setArchiveTarget({
											projectId: projectAreaId,
											sessionId: chat.sessionId,
											title: chat.title,
										})
									}
									className="shrink-0 px-xs text-text-muted"
								>
									<Archive className="size-3.5" />
								</DropdownMenuItem>
								<DropdownMenuItem
									data-testid="closed-chat-delete"
									aria-label={`Move ${chat.title} to trash`}
									title="Move chat to trash"
									onSelect={() => {
										void getTransport()
											.request("session.delete", {
												projectId: projectAreaId,
												sessionId: chat.sessionId,
											})
											.then(() => useAppStore.getState().deleteChat(projectAreaId, chat.sessionId))
											.catch((cause) => {
												const state = useAppStore.getState();
												if (
													!state.removedProjectAreaIds[projectAreaId] &&
													!state.deletedSessionsByProjectArea[projectAreaId]?.[chat.sessionId]
												) {
													toast.error(errorText(cause), "Couldn't delete the chat");
												}
											});
									}}
									className="shrink-0 px-xs text-text-muted focus:text-feedback-error"
								>
									<Trash2 className="size-3.5" />
								</DropdownMenuItem>
							</DropdownMenuGroup>
						))
					)}
					<DropdownMenuSeparator />
					<DropdownMenuLabel>Archived</DropdownMenuLabel>
					{archivedLoading ? (
						<p
							role="status"
							aria-live="polite"
							className="px-sm py-xs text-text-muted tr-text-metadata"
						>
							Loading archived chats…
						</p>
					) : archivedError ? (
						<DropdownMenuItem
							aria-label="Retry loading archived chats"
							onSelect={() => void loadArchived()}
						>
							Couldn't load archived chats · Retry
						</DropdownMenuItem>
					) : archived.length === 0 ? (
						<p className="px-sm py-xs text-text-muted tr-text-metadata">No archived chats</p>
					) : (
						archived.map((session) => (
							<DropdownMenuItem
								key={session.sessionId}
								disabled={restoring === session.sessionId}
								aria-label={
									restoring === session.sessionId
										? `Restoring ${session.title}`
										: `Restore ${session.title}`
								}
								onSelect={() => restore(session.sessionId)}
							>
								<span className="min-w-0 flex-1 truncate">{session.title}</span>
								<span className="shrink-0 text-text-muted tr-text-metadata">
									{relativeTime(session.updatedAt)}
								</span>
								<ArchiveRestore className="size-3.5" />
							</DropdownMenuItem>
						))
					)}
				</DropdownMenuContent>
			</DropdownMenu>
			{renameTarget ? (
				<RenameSessionDialog
					target={renameTarget}
					open
					onOpenChange={(next) => !next && setRenameTarget(null)}
				/>
			) : null}
			{archiveTarget ? (
				<ArchiveSessionDialog
					target={archiveTarget}
					open
					onOpenChange={(next) => !next && setArchiveTarget(null)}
				/>
			) : null}
		</>
	);
}

const EMPTY_CHATS: ClosedChat[] = [];
