// gooseberry/webui/src/workspace/projects/add-project-menu.tsx
import type { Project } from "@gooseberry/contracts";
import { Folder } from "lucide-react";
import type { ReactNode } from "react";
import {
	DropdownMenu,
	DropdownMenuContent,
	DropdownMenuGroup,
	DropdownMenuItem,
	DropdownMenuLabel,
	DropdownMenuSeparator,
	DropdownMenuTrigger,
} from "../../components/ui/dropdown-menu";

export function AddProjectMenu({
	recentProjects,
	onOpen,
	onOpenRecent,
	align = "end",
	children,
}: {
	recentProjects: Project[];
	onOpen: () => void;
	onOpenRecent: (path: string) => void;
	align?: "start" | "center" | "end";
	children: ReactNode;
}) {
	return (
		<DropdownMenu>
			<DropdownMenuTrigger asChild>{children}</DropdownMenuTrigger>
			<DropdownMenuContent align={align}>
				<DropdownMenuItem data-testid="menu-open-project" onSelect={() => onOpen()}>
					<Folder />
					<span>Open project</span>
				</DropdownMenuItem>
				{recentProjects.length > 0 && (
					<>
						<DropdownMenuSeparator />
						<DropdownMenuLabel>Recents</DropdownMenuLabel>
						<DropdownMenuGroup>
							{recentProjects.map((project) => (
								<DropdownMenuItem
									key={project.id}
									onSelect={() => project.roots[0] && onOpenRecent(project.roots[0])}
									title={project.roots[0]}
								>
									<Folder />
									<span className="truncate">{project.roots[0]}</span>
								</DropdownMenuItem>
							))}
						</DropdownMenuGroup>
					</>
				)}
			</DropdownMenuContent>
		</DropdownMenu>
	);
}

// gooseberry/webui/src/workspace/projects/add-project-menu.svelte
<script lang="ts">
import type { Project } from "@gooseberry/contracts";
import type { Snippet } from "svelte";
import { mewa } from "../../../vendor/mewa-svelte/index.js";
import { behavior as dropdownBehavior } from "../../../vendor/mewa-ui/components/dropdown-menu.js";
import Icon from "../../components/icon.svelte";

interface Props {
	recentProjects: Project[];
	onOpen: () => void;
	onOpenRecent: (path: string) => void;
	trigger: Snippet<[string]>;
	align?: "start" | "end";
}

let { recentProjects, onOpen, onOpenRecent, trigger, align = "end" }: Props = $props();
const componentId = $props.id();
const menuId = `add-project-${componentId}`;
let menu: HTMLElement;

function choose(callback: () => void): void {
	menu?.hidePopover();
	callback();
}
</script>

<div class="contents" {@attach mewa(dropdownBehavior)}>
	{@render trigger(menuId)}
	<div
		bind:this={menu}
		id={menuId}
		popover="auto"
		role="menu"
		class="dropdown-menu-content"
		data-align={align}
	>
		<button
			type="button"
			role="menuitem"
			class="dropdown-menu-item"
			data-testid="menu-open-project"
			onclick={() => choose(onOpen)}
		>
			<Icon name="folder" size={16} />
			<span>Open project</span>
		</button>
		{#if recentProjects.length > 0}
			<div class="dropdown-menu-separator"></div>
			<div class="dropdown-menu-label">Recents</div>
			<div role="group">
				{#each recentProjects as project (project.id)}
					<button
						type="button"
						role="menuitem"
						class="dropdown-menu-item"
						title={project.roots[0]}
						onclick={() => {
							const path = project.roots[0];
							if (path) choose(() => onOpenRecent(path));
						}}
					>
						<Icon name="folder" size={16} />
						<span class="truncate">{project.roots[0]}</span>
					</button>
				{/each}
			</div>
		{/if}
	</div>
</div>

<style>
	.dropdown-menu-content[data-align="end"] {
		left: auto;
		right: anchor(right);
	}
</style>
