// gooseberry/webui/src/workspace/project-customization-dialog.tsx
import {
	normalizeProjectName,
	PROJECT_ICONS,
	PROJECT_NAME_MAX_LENGTH,
	type Project,
	type ProjectIcon as ProjectIconName,
} from "@gooseberry/contracts";
import { type FormEvent, useEffect, useState } from "react";
import { Button } from "../components/ui/button";
import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogFooter,
	DialogHeader,
	DialogTitle,
} from "../components/ui/dialog";
import { errorText, getTransport } from "../connection";
import { toast, useAppStore } from "../store";
import { ProjectIcon } from "./project-icon";

const ICON_LABELS: Record<ProjectIconName, string> = {
	folder: "Folder",
	code: "Code",
	book: "Book",
	flask: "Experiment",
	rocket: "Rocket",
	sparkles: "Sparkles",
};

export function ProjectCustomizationDialog({
	project,
	open,
	onOpenChange,
}: {
	project: Project;
	open: boolean;
	onOpenChange: (open: boolean) => void;
}) {
	const [name, setName] = useState(project.name);
	const [icon, setIcon] = useState<ProjectIconName>(project.icon ?? "folder");
	const [error, setError] = useState<string | null>(null);
	const [busy, setBusy] = useState(false);

	useEffect(() => {
		if (!open) return;
		setName(project.name);
		setIcon(project.icon ?? "folder");
		setError(null);
	}, [open, project.name, project.icon]);

	const submit = (event: FormEvent) => {
		event.preventDefault();
		let normalized: string;
		try {
			normalized = normalizeProjectName(name);
		} catch (cause) {
			setError(errorText(cause));
			return;
		}
		setBusy(true);
		setError(null);
		void getTransport()
			.request("project.update", { id: project.id, name: normalized, icon })
			.then((updated) => {
				useAppStore.getState().applyProjectUpdated(updated);
				onOpenChange(false);
			})
			.catch((cause) => {
				setError(errorText(cause));
				toast.error(errorText(cause), "Couldn't update the project");
			})
			.finally(() => setBusy(false));
	};

	return (
		<Dialog open={open} onOpenChange={(next) => !busy && onOpenChange(next)}>
			<DialogContent data-testid="project-customization-dialog" className="max-w-[26rem]">
				<form className="flex flex-col gap-lg" onSubmit={submit}>
					<DialogHeader>
						<DialogTitle>Customize project</DialogTitle>
						<DialogDescription>Choose the name and icon shown in Gooseberry.</DialogDescription>
					</DialogHeader>
					<label className="flex flex-col gap-xs tr-text-ui text-text-default">
						<span>Name</span>
						<input
							autoFocus
							value={name}
							maxLength={PROJECT_NAME_MAX_LENGTH}
							disabled={busy}
							onChange={(event) => setName(event.target.value)}
							className="rounded-[var(--radius-sm)] border border-border-default bg-control-bg px-sm py-xs outline-none focus-visible:ring-2 focus-visible:ring-primary"
						/>
					</label>
					<fieldset className="flex flex-col gap-xs" disabled={busy}>
						<legend className="mb-xs tr-text-ui text-text-default">Icon</legend>
						<div className="grid grid-cols-3 gap-xs">
							{PROJECT_ICONS.map((candidate) => (
								<label
									key={candidate}
									data-selected={candidate === icon || undefined}
									className="flex cursor-pointer items-center gap-xs rounded-[var(--radius-sm)] border border-border-default px-sm py-xs text-text-muted tr-text-metadata hover:bg-control-bg-hovered focus-within:ring-2 focus-within:ring-primary data-[selected]:border-primary data-[selected]:bg-primary-subtle data-[selected]:text-text-default"
								>
									<input
										type="radio"
										name="project-icon"
										value={candidate}
										checked={candidate === icon}
										onChange={() => setIcon(candidate)}
										className="sr-only"
									/>
									<ProjectIcon icon={candidate} className="size-3.5" />
									{ICON_LABELS[candidate]}
								</label>
							))}
						</div>
					</fieldset>
					{error ? (
						<p role="alert" className="text-feedback-error tr-text-metadata">
							{error}
						</p>
					) : null}
					<DialogFooter>
						<Button
							type="button"
							variant="outline"
							disabled={busy}
							onClick={() => onOpenChange(false)}
						>
							Cancel
						</Button>
						<Button
							type="submit"
							disabled={busy || !name.trim()}
							data-testid="project-customization-save"
						>
							{busy ? "Saving…" : "Save"}
						</Button>
					</DialogFooter>
				</form>
			</DialogContent>
		</Dialog>
	);
}

// gooseberry/webui/src/workspace/projects/project-customization-dialog.svelte
<script lang="ts">
import {
	normalizeProjectName,
	PROJECT_ICONS,
	PROJECT_NAME_MAX_LENGTH,
	type Project,
	type ProjectIcon as ProjectIconName,
} from "@gooseberry/contracts";
import Button from "../../components/button.svelte";
import Dialog from "../../components/dialog.svelte";
import { errorText, getTransport } from "../../connection";
import { appStoreApi, toast } from "../../store";
import ProjectIcon from "./project-icon.svelte";

const ICON_LABELS: Record<ProjectIconName, string> = {
	folder: "Folder",
	code: "Code",
	book: "Book",
	flask: "Experiment",
	rocket: "Rocket",
	sparkles: "Sparkles",
};

interface Props {
	project: Project;
	open?: boolean;
	onOpenChange?: (open: boolean) => void;
}

let { project, open = $bindable(false), onOpenChange }: Props = $props();
let name = $state("");
let icon = $state<ProjectIconName>("folder");
let error = $state<string | null>(null);
let busy = $state(false);

function setOpen(next: boolean): boolean {
	if (busy && !next) return false;
	open = next;
	onOpenChange?.(next);
	return true;
}

$effect(() => {
	if (!open) return;
	name = project.name;
	icon = project.icon ?? "folder";
	error = null;
});

function submit(event: SubmitEvent): void {
	event.preventDefault();
	let normalized: string;
	try {
		normalized = normalizeProjectName(name);
	} catch (cause) {
		error = errorText(cause);
		return;
	}
	busy = true;
	error = null;
	void getTransport()
		.request("project.update", { id: project.id, name: normalized, icon })
		.then((updated) => {
			appStoreApi.getState().applyProjectUpdated(updated);
			open = false;
			onOpenChange?.(false);
		})
		.catch((cause) => {
			error = errorText(cause);
			toast.error(errorText(cause), "Couldn't update the project");
		})
		.finally(() => {
			busy = false;
		});
}
</script>

<Dialog
	open={open}
	title="Customize project"
	description="Choose the name and icon shown in Gooseberry."
	testid="project-customization-dialog"
	class="max-w-[26rem]"
	onOpenChange={setOpen}
>
	<form id="project-customization-form" class="form flex flex-col gap-lg" onsubmit={submit}>
		<label class="text-field">
			<span class="text-field-label">Name</span>
			<!-- svelte-ignore a11y_autofocus (A newly opened customization dialog starts in its primary field.) -->
			<input
					class="text-field-input"
					autofocus
				bind:value={name}
				maxlength={PROJECT_NAME_MAX_LENGTH}
				disabled={busy}
			/>
		</label>
		<fieldset class="radio-group" disabled={busy}>
			<legend class="field-label">Icon</legend>
			<div class="grid grid-cols-3 gap-xs">
				{#each PROJECT_ICONS as candidate}
					<label class="radio-card">
						<input
							type="radio"
							class="radio"
							name="project-icon"
							value={candidate}
							checked={candidate === icon}
							onchange={() => (icon = candidate)}
						/>
						<span class="flex items-center gap-xs">
							<ProjectIcon icon={candidate} size={14} /> {ICON_LABELS[candidate]}
						</span>
					</label>
				{/each}
			</div>
		</fieldset>
		{#if error}<p role="alert" class="field-error">{error}</p>{/if}
	</form>
	{#snippet actions()}
		<Button variant="outline" disabled={busy} onclick={() => setOpen(false)}>Cancel</Button>
		<Button
			type="submit"
			form="project-customization-form"
			disabled={busy || !name.trim()}
			data-testid="project-customization-save"
		>
			{busy ? "Saving…" : "Save"}
		</Button>
	{/snippet}
</Dialog>
