// mewa-code/webui/src/panels/ProjectTree.tsx
import type { Project } from "@mewa-code/contracts";
import { Folder, FolderOpen, Plus, X } from "lucide-react";
import { useRef } from "react";
import { Button } from "@/components/ui/button";
import { toast, useAppStore } from "../store";
import { errorText, getTransport } from "../transport";
import { AddProjectMenu } from "./AddProjectMenu";
import { enterDefaultWorkspace } from "./defaultWorkspace";
import { useOpenProject } from "./useOpenProject";

export function ProjectTree() {
	const projects = useAppStore((state) => state.projects);
	const recentProjects = useAppStore((state) => state.recentProjects);
	const selectedProjectId = useAppStore((state) => state.selectedProjectId);
	const addButton = useRef<HTMLButtonElement>(null);

	const selectProject = async (project: Project) => {
		useAppStore.getState().selectProject(project.id);
		await enterDefaultWorkspace(project.id);
	};

	const { openProject, pickAndOpen, dialogs } = useOpenProject((project) => selectProject(project));

	const closeProject = (project: Project) => {
		void getTransport()
			.request("project.close", { id: project.id })
			.catch((error) => toast.error(errorText(error), `Couldn't close ${project.name}`));
	};

	return (
		<nav className="flex flex-col gap-sm">
			<header className="flex h-7 items-center justify-between pr-xs pl-sm">
				<span className="tr-text-eyebrow text-text-muted">Projects</span>
				<AddProjectMenu
					recentProjects={recentProjects}
					onOpen={() => void pickAndOpen()}
					onOpenRecent={(path) => void openProject(path)}
				>
					<Button
						ref={addButton}
						variant="ghost"
						size="icon"
						data-testid="add-project-menu"
						aria-label="Add project"
					>
						<Plus className="size-4" />
					</Button>
				</AddProjectMenu>
			</header>

			<ul className="flex flex-col gap-2xs">
				{projects.map((project) => {
					const selected = selectedProjectId === project.id;
					return (
						<li key={project.id} className="group flex min-w-0 items-center">
							<button
								type="button"
								data-testid="project-row"
								data-project-id={project.id}
								data-selected={selected || undefined}
								onClick={() => void selectProject(project)}
								title={project.path}
								className="flex min-w-0 flex-1 items-center gap-sm rounded-[var(--radius-sm)] px-sm py-xs text-left outline-none hover:bg-control-bg-hovered focus-visible:ring-2 focus-visible:ring-primary data-[selected]:bg-control-bg-selected"
							>
								{selected ? (
									<FolderOpen className="size-4 shrink-0 text-primary" />
								) : (
									<Folder className="size-4 shrink-0 text-text-muted" />
								)}
								<span className="min-w-0 flex-1">
									<span className="block truncate tr-text-ui text-text-default">
										{project.name}
									</span>
									<span className="block truncate tr-text-metadata text-text-muted">
										{project.path}
									</span>
								</span>
							</button>
							<button
								type="button"
								aria-label={`Remove ${project.name} from Mewa`}
								title="Remove from Mewa"
								onClick={() => closeProject(project)}
								className="invisible flex size-7 shrink-0 items-center justify-center rounded-[var(--radius-sm)] text-text-muted hover:bg-control-bg-hovered hover:text-text-default group-hover:visible focus:visible"
							>
								<X className="size-3.5" />
							</button>
						</li>
					);
				})}
			</ul>
			{projects.length === 0 ? (
				<p className="px-sm py-xs tr-text-metadata text-text-muted">
					Open a directory to start a project.
				</p>
			) : null}
			{dialogs}
		</nav>
	);
}

// gooseberry/webui/src/workspace/projects/project-tree.svelte
<script lang="ts">
import type { Project } from "@gooseberry/contracts";
import Button from "../../components/button.svelte";
import Icon from "../../components/icon.svelte";
import { errorText, getTransport } from "../../connection";
import { appStore, appStoreApi, toast } from "../../store";
import { enterDefaultProjectArea } from "../navigation/default-project-area";
import AddProjectMenu from "./add-project-menu.svelte";
import OpenProjectDialogs from "./open-project-dialogs.svelte";
import ProjectCustomizationDialog from "./project-customization-dialog.svelte";
import ProjectIcon from "./project-icon.svelte";
import ProjectSessions from "./project-sessions.svelte";

interface ProjectOpener {
	openProject: (path: string) => Promise<void>;
	pickAndOpen: () => void;
}

let opener = $state<ProjectOpener>();
let customizeProject = $state<Project | null>(null);

async function selectProject(project: Project): Promise<void> {
	appStoreApi.getState().selectProject(project.id);
	await enterDefaultProjectArea(project.id);
}

function closeProject(project: Project): void {
	void getTransport()
		.request("project.close", { id: project.id })
		.catch((cause) => toast.error(errorText(cause), `Couldn't close ${project.name}`));
}
</script>

<nav class="tree flex flex-col gap-sm" aria-label="Projects">
	<header class="flex h-7 items-center justify-between pr-xs pl-sm">
		<span class="tr-text-eyebrow text-text-muted">Projects</span>
		{#snippet addTrigger(menuId: string)}
			<Button
				variant="ghost"
				size="icon"
				data-testid="add-project-menu"
				data-dropdown-menu-trigger={menuId}
				aria-haspopup="menu"
				aria-controls={menuId}
				aria-expanded="false"
				aria-label="Add project"
			>
				<Icon name="plus" size={16} />
			</Button>
		{/snippet}
		<AddProjectMenu
			recentProjects={$appStore.recentProjects}
			onOpen={() => opener?.pickAndOpen()}
			onOpenRecent={(path) => void opener?.openProject(path)}
			trigger={addTrigger}
		/>
	</header>

	<ul class="tree-group flex flex-col gap-2xs">
		{#each $appStore.projects as project (project.id)}
			{@const selected = $appStore.selectedProjectId === project.id}
			<li class="tree-item group flex min-w-0 flex-col">
				<div class="flex w-full min-w-0 items-center">
					<button
						type="button"
						data-testid="project-row"
						data-project-id={project.id}
						data-selected={selected || undefined}
						title={project.roots[0]}
						class="tree-leaf min-w-0 flex-1"
						onclick={() => void selectProject(project)}
					>
						<ProjectIcon
							icon={project.icon ?? "folder"}
							size={16}
							class={selected ? "text-primary" : "text-text-muted"}
						/>
						<span class="min-w-0 flex-1">
							<span class="block truncate tr-text-ui text-text-default">{project.name}</span>
							<span class="block truncate tr-text-metadata text-text-muted">{project.roots[0]}</span>
						</span>
					</button>
					<Button
						variant="ghost"
						size="icon-sm"
						aria-label={`Customize ${project.name}`}
						title="Customize project"
						class="invisible group-hover:visible focus:visible"
						onclick={() => (customizeProject = project)}
					>
						<Icon name="settings-2" size={14} />
					</Button>
					<Button
						variant="ghost"
						size="icon-sm"
						aria-label={`Remove ${project.name} from gooseberry`}
						title="Remove from gooseberry"
						class="invisible group-hover:visible focus:visible"
						onclick={() => closeProject(project)}
					>
						<Icon name="x" size={14} />
					</Button>
				</div>
				{#if selected}
					<ul class="tree-group flex w-full flex-col gap-2xs py-2xs pl-lg">
						<ProjectSessions {project} />
					</ul>
				{/if}
			</li>
		{/each}
	</ul>
	{#if $appStore.projects.length === 0}
		<p class="px-sm py-xs tr-text-metadata text-text-muted">Open a directory to start a project.</p>
	{/if}
</nav>

<OpenProjectDialogs bind:this={opener} onOpened={selectProject} />
{#if customizeProject}
	<ProjectCustomizationDialog
		project={customizeProject}
		open
		onOpenChange={(next) => { if (!next) customizeProject = null; }}
	/>
{/if}
