// gooseberry/webui/src/chat/tool-card.tsx
import { Check, ChevronRight, Loader2, X } from "lucide-react";
import { cn } from "@/lib";
import { useFold } from "./fold-state";
import { getToolRenderer, getToolSummary, resolveProminence } from "./tool-registry";
import { McpAppView } from "./tools/apps/mcp-app-view";
import type { ToolResultState } from "./types";

export function ToolCard({
	toolCallId,
	toolName,
	args,
	tool,
	dead = false,
	streaming,
	projectAreaRoot,
}: {
	toolCallId: string;
	toolName: string;
	args: Record<string, unknown>;
	tool: ToolResultState | undefined;
	dead?: boolean;
	streaming: boolean;
	projectAreaRoot?: string | undefined;
}) {
	const status = tool?.status ?? (dead ? "error" : "running");
	const isError = status === "error";
	const Renderer = getToolRenderer(toolName);
	const renderProps = {
		toolCallId,
		toolName,
		args,
		result: tool?.raw,
		app: tool?.app,
		subagentActivity: tool?.subagentActivity,
		status,
		projectAreaRoot,
		streaming,
	};
	const summary = getToolSummary(toolName, renderProps);

	const autoExpand = isError || (resolveProminence(toolName).defaultExpanded && status === "done");
	const [expanded, toggle] = useFold(toolCallId, autoExpand);

	return (
		<div
			data-testid="tool-card"
			data-tool={toolName}
			data-status={status}
			data-expanded={expanded}
			className="rounded-[var(--radius-sm)] border border-border-default bg-container-elevated-bg"
		>
			<button
				type="button"
				data-testid="tool-card-toggle"
				aria-expanded={expanded}
				onClick={toggle}
				className="flex w-full cursor-pointer select-none items-center gap-xs px-sm py-xs text-left tr-text-metadata outline-none focus-visible:ring-2 focus-visible:ring-primary"
			>
				{status === "running" ? (
					<Loader2 className="size-3 shrink-0 animate-spin text-text-muted motion-reduce:animate-none" />
				) : isError ? (
					<X className="size-3 shrink-0 text-feedback-error" />
				) : (
					<Check className="size-3 shrink-0 text-feedback-success" />
				)}
				<span className="shrink-0 text-text-default">{toolName}</span>
				{summary ? (
					<span className="min-w-0 flex-1 truncate text-text-muted" title={summary}>
						{summary}
					</span>
				) : (
					<span className="flex-1" />
				)}
				<ChevronRight
					className={`size-3 shrink-0 text-text-muted transition-transform ${expanded ? "rotate-90" : ""}`}
				/>
			</button>
			{expanded ? (
				<div
					className={cn(
						"flex flex-col items-start gap-sm px-sm pb-xs",
						isError && "text-feedback-error",
					)}
				>
					<Renderer {...renderProps} />
					<McpAppView {...renderProps} />
				</div>
			) : null}
		</div>
	);
}

// gooseberry/webui/src/chat/render/tool-card.svelte
<script lang="ts">
import { untrack } from "svelte";
import Icon from "../../components/icon.svelte";
import { readFold, toggleFold } from "../runtime/fold-state";
import type { ToolResultState } from "../runtime/types";
import McpAppView from "../tools/apps/mcp-app-view.svelte";
import { getToolRenderer, getToolSummary, resolveProminence } from "./tool-registry";

interface Props {
	toolCallId: string;
	toolName: string;
	args: Record<string, unknown>;
	tool: ToolResultState | undefined;
	dead?: boolean;
	streaming: boolean;
	projectAreaRoot?: string | undefined;
}

let {
	toolCallId,
	toolName,
	args,
	tool,
	dead = false,
	streaming,
	projectAreaRoot,
}: Props = $props();
let status = $derived(tool?.status ?? (dead ? "error" : "running"));
let isError = $derived(status === "error");
let Renderer = $derived(getToolRenderer(toolName));
let renderProps = $derived({
	toolCallId,
	toolName,
	args,
	result: tool?.raw,
	app: tool?.app,
	subagentActivity: tool?.subagentActivity,
	status,
	projectAreaRoot,
	streaming,
});
let summary = $derived(getToolSummary(toolName, renderProps));
let autoExpand = $derived(
	isError || (resolveProminence(toolName).defaultExpanded && status === "done"),
);
let expanded = $state(untrack(() => readFold(toolCallId, autoExpand)));

$effect(() => {
	if (autoExpand && !expanded && readFold(toolCallId, autoExpand)) expanded = true;
});
</script>

<div
	data-testid="tool-card"
	data-tool={toolName}
	data-status={status}
	data-expanded={expanded}
	class="rounded-[var(--radius-sm)] border border-border-default bg-container-elevated-bg"
>
	<button
		type="button"
		data-testid="tool-card-toggle"
		aria-expanded={expanded}
		onclick={() => (expanded = toggleFold(toolCallId, expanded))}
		class="flex w-full cursor-pointer select-none items-center gap-xs px-sm py-xs text-left tr-text-metadata outline-none focus-visible:ring-2 focus-visible:ring-primary"
	>
		<Icon
			name={status === "running" ? "loader-circle" : isError ? "x" : "check"}
			size={12}
			class={`shrink-0 ${status === "running" ? "animate-spin text-text-muted motion-reduce:animate-none" : isError ? "text-feedback-error" : "text-feedback-success"}`}
		/>
		<span class="shrink-0 text-text-default">{toolName}</span>
		{#if summary}<span class="min-w-0 flex-1 truncate text-text-muted" title={summary}>{summary}</span>
		{:else}<span class="flex-1"></span>{/if}
		<Icon name="chevron-right" size={12} class={`shrink-0 text-text-muted transition-transform ${expanded ? "rotate-90" : ""}`} />
	</button>
	{#if expanded}
		<div class={`flex flex-col items-start gap-sm px-sm pb-xs ${isError ? "text-feedback-error" : ""}`}>
			<Renderer {...renderProps} />
			<McpAppView {...renderProps} />
		</div>
	{/if}
</div>
