// gooseberry/webui/src/files/changes/changes-tree.svelte
<script lang="ts">
import type { GitFileChange } from "@gooseberry/contracts";
import type { TabIntent } from "../../store";
import TreeRow from "../tree/tree-row.svelte";
import ChangeRowActions, { ROW_MENU_SLOT } from "./change-row-actions.svelte";
import { buildChangesTree, type ChangeTreeNode, statusNameClass } from "./changes-model";
import DiffStatBadge from "./diff-stat-badge.svelte";

interface Props {
	changes: readonly GitFileChange[];
	onOpen: (path: string, intent: TabIntent) => void;
	isActive: (path: string) => boolean;
}

let { changes, onOpen, isActive }: Props = $props();
let nodes = $derived(buildChangesTree(changes));
let collapsedPaths = $state<ReadonlySet<string>>(new Set());

function toggle(path: string): void {
	const next = new Set(collapsedPaths);
	if (next.has(path)) next.delete(path);
	else next.add(path);
	collapsedPaths = next;
}
</script>

{#snippet nodeRow(node: ChangeTreeNode)}
	{#if node.kind === "file"}
		<li>
			{#snippet trailing()}
				<DiffStatBadge added={node.added} removed={node.removed} />
			{/snippet}
			{#snippet row(oncontextmenu: (event: MouseEvent) => void)}
				<TreeRow
					testid="change-node"
					{oncontextmenu}
					kind="file"
					highlight="wrapper"
					active={isActive(node.path)}
					dataStatus={node.status}
					label={node.name}
					labelClassName={statusNameClass(node.status)}
					onclick={() => onOpen(node.path, "preview")}
					ondblclick={() => onOpen(node.path, "keep")}
					{trailing}
				/>
			{/snippet}
			<ChangeRowActions
				path={node.path}
				active={isActive(node.path)}
				onView={() => onOpen(node.path, "preview")}
				children={row}
			/>
		</li>
	{:else}
		{@const expanded = !collapsedPaths.has(node.path)}
		<li>
			<div class="flex min-w-0 items-center">
				{#snippet trailing()}
					<DiffStatBadge added={node.added} removed={node.removed} />
				{/snippet}
				<TreeRow
					testid="change-tree-folder"
					kind="dir"
					{expanded}
					label={node.name}
					onclick={() => toggle(node.path)}
					{trailing}
				/>
				<span class={ROW_MENU_SLOT}></span>
			</div>
			{#if expanded}
				<ul class="tree-group flex flex-col pl-md">
					{#each node.children as child (child.path)}
						{@render nodeRow(child)}
					{/each}
				</ul>
			{/if}
		</li>
	{/if}
{/snippet}

<ul class="tree tree-group flex flex-col">
	{#each nodes as node (node.path)}
		{@render nodeRow(node)}
	{/each}
</ul>

// mewa-code/webui/src/panels/changes-tree.tsx
import type { GitFileChange } from "@mewa-code/contracts";
import { useState } from "react";
import type { TabIntent } from "../store";
import { ChangeRowActions, ROW_MENU_SLOT } from "./change-row-actions";
import { buildChangesTree, type ChangeTreeNode, statusNameClass } from "./changes-model";
import { DiffStatBadge } from "./diff-stat-badge";
import { TreeRow } from "./tree-row";

export function ChangesTree({
	changes,
	onOpen,
	isActive,
}: {
	changes: readonly GitFileChange[];
	onOpen: (path: string, intent: TabIntent) => void;
	isActive: (path: string) => boolean;
}) {
	return (
		<ul className="flex flex-col">
			{buildChangesTree(changes).map((node) => (
				<ChangeNodeRow key={node.path} node={node} onOpen={onOpen} isActive={isActive} />
			))}
		</ul>
	);
}

function ChangeNodeRow({
	node,
	onOpen,
	isActive,
}: {
	node: ChangeTreeNode;
	onOpen: (path: string, intent: TabIntent) => void;
	isActive: (path: string) => boolean;
}) {
	const [expanded, setExpanded] = useState(true);

	if (node.kind === "file") {
		return (
			<li>
				<ChangeRowActions
					path={node.path}
					active={isActive(node.path)}
					onView={() => onOpen(node.path, "preview")}
				>
					{({ onContextMenu }) => (
						<TreeRow
							testid="change-node"
							onContextMenu={onContextMenu}
							kind="file"
							highlight="wrapper"
							active={isActive(node.path)}
							dataStatus={node.status}
							label={node.name}
							labelClassName={statusNameClass(node.status)}
							onClick={() => onOpen(node.path, "preview")}
							onDoubleClick={() => onOpen(node.path, "keep")}
							trailing={<DiffStatBadge added={node.added} removed={node.removed} />}
						/>
					)}
				</ChangeRowActions>
			</li>
		);
	}

	return (
		<li>
			<div className="flex min-w-0 items-center">
				<TreeRow
					testid="change-tree-folder"
					kind="dir"
					expanded={expanded}
					label={node.name}
					onClick={() => setExpanded((v) => !v)}
					trailing={<DiffStatBadge added={node.added} removed={node.removed} />}
				/>
				<span className={ROW_MENU_SLOT} />
			</div>
			{expanded && (
				<ul className="flex flex-col pl-md">
					{node.children.map((child) => (
						<ChangeNodeRow key={child.path} node={child} onOpen={onOpen} isActive={isActive} />
					))}
				</ul>
			)}
		</li>
	);
}
